### ISSUE TITLE
JSF/Primefaces doesn't work, when Primefaces is inside WEB-INF/lib [PAXWEB-1244]

### ISSUE THREAD

**Issue by ops4j-issues** [ops4j/org.ops4j.pax.web#1525]
**[Grzegorz Grzybek](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:9c7cd322-6f60-46ab-9235-bab9ac2f59f6)** created **[PAXWEB-1244](https://ops4j1.jira.com/browse/PAXWEB-1244)** 

I had a case when primefaces + myfaces 2.2.x were embedded inside war's `WEB-INF/lib`. I checked that almost everything works (JSF factories are properly discovered and everything from primefaces `META-INF/faces-config.xml` is properly registered.

But unfortunately actual facelet taglibs (files ending with `.taglib.xml`) are not loaded properly.

The culprit is `org.apache.myfaces.view.facelets.util.Classpath#_searchResource` method and under normal Tomcat (no OSGi) it's invoked like this:

```
"main@1" prio=5 tid=0x1 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at org.apache.myfaces.view.facelets.util.Classpath._searchResource(Classpath.java:91)
	  at org.apache.myfaces.view.facelets.util.Classpath.search(Classpath.java:68)
	  at org.apache.myfaces.view.facelets.compiler.DefaultFaceletConfigResourceProvider.getFaceletTagLibConfigurationResources(DefaultFaceletConfigResourceProvider.java:74)
	  at org.apache.myfaces.config.DefaultFacesConfigurationProvider.getFaceletTaglibFacesConfig(DefaultFacesConfigurationProvider.java:814)
	  at org.apache.myfaces.config.DefaultFacesConfigurationMerger.getFacesConfigData(DefaultFacesConfigurationMerger.java:116)
	  at org.apache.myfaces.config.FacesConfigurator.configure(FacesConfigurator.java:592)
	  at org.apache.myfaces.webapp.AbstractFacesInitializer.buildConfiguration(AbstractFacesInitializer.java:416)
	  at org.apache.myfaces.webapp.Jsp21FacesInitializer.initContainerIntegration(Jsp21FacesInitializer.java:73)
	  at org.apache.myfaces.webapp.AbstractFacesInitializer.initFaces(AbstractFacesInitializer.java:172)
	  at org.apache.myfaces.webapp.StartupServletContextListener.contextInitialized(StartupServletContextListener.java:121)
	  at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4683)
...
```

Under pax-web:

```
"paxweb-extender-1-thread-2@11110" prio=5 tid=0x9b nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at org.apache.myfaces.view.facelets.util.Classpath._searchResource(Classpath.java:79)
	  at org.apache.myfaces.view.facelets.util.Classpath.search(Classpath.java:68)
	  at org.apache.myfaces.view.facelets.compiler.DefaultFaceletConfigResourceProvider.getFaceletTagLibConfigurationResources(DefaultFaceletConfigResourceProvider.java:74)
	  at org.apache.myfaces.config.DefaultFacesConfigurationProvider.getFaceletTaglibFacesConfig(DefaultFacesConfigurationProvider.java:814)
	  at org.apache.myfaces.config.DefaultFacesConfigurationMerger.getFacesConfigData(DefaultFacesConfigurationMerger.java:116)
	  at org.apache.myfaces.config.FacesConfigurator.configure(FacesConfigurator.java:592)
	  at org.apache.myfaces.webapp.AbstractFacesInitializer.buildConfiguration(AbstractFacesInitializer.java:416)
	  at org.apache.myfaces.webapp.Jsp21FacesInitializer.initContainerIntegration(Jsp21FacesInitializer.java:73)
	  at org.apache.myfaces.webapp.AbstractFacesInitializer.initFaces(AbstractFacesInitializer.java:172)
	  at org.apache.myfaces.webapp.StartupServletContextListener.contextInitialized(StartupServletContextListener.java:121)
	  at org.ops4j.pax.web.service.jetty.internal.HttpServiceContext$3.call(HttpServiceContext.java:338)
	  at org.ops4j.pax.web.service.jetty.internal.HttpServiceContext$3.call(HttpServiceContext.java:334)
	  at org.ops4j.pax.swissbox.core.ContextClassLoaderUtils.doWithClassLoader(ContextClassLoaderUtils.java:60)
	  at org.ops4j.pax.web.service.jetty.internal.HttpServiceContext.callContextInitialized(HttpServiceContext.java:333)
	  at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:888)
	  at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:357)
	  at org.ops4j.pax.web.service.jetty.internal.HttpServiceContext.startContext(HttpServiceContext.java:391)
	  at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:821)
	  at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:276)
	  at org.ops4j.pax.web.service.jetty.internal.HttpServiceContext.doStart(HttpServiceContext.java:267)
	  at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	  - locked <0x2c87> (a java.lang.Object)
	  at org.ops4j.pax.web.service.jetty.internal.JettyServerImpl$1.start(JettyServerImpl.java:329)
	  at org.ops4j.pax.web.service.internal.HttpServiceStarted.end(HttpServiceStarted.java:1261)
	  at org.ops4j.pax.web.service.internal.HttpServiceProxy.end(HttpServiceProxy.java:456)
	  at org.ops4j.pax.web.extender.war.internal.RegisterWebAppVisitorWC.end(RegisterWebAppVisitorWC.java:405)
	  at org.ops4j.pax.web.extender.war.internal.model.WebApp.accept(WebApp.java:658)
	  at org.ops4j.pax.web.extender.war.internal.WebAppPublisher$WebAppDependencyListener.register(WebAppPublisher.java:228)
	  at org.ops4j.pax.web.extender.war.internal.WebAppPublisher$WebAppDependencyListener.addingService(WebAppPublisher.java:173)
	  at org.ops4j.pax.web.extender.war.internal.WebAppPublisher$WebAppDependencyListener.addingService(WebAppPublisher.java:129)
...
```

The prefix of resource to search (recursively) is `META-INF/` and suffix is `.taglib.xml`.

In Tomcat, these URLs are returned from `java.lang.ClassLoader#getResources()`:

```
 0 = {java.net.URL@4038} "jar:file:/data/servers/apache-tomcat-9.0.24/webapps/test-jsf-primefaces-0.1.0.BUILD-SNAPSHOT/WEB-INF/lib/jul-to-slf4j-1.7.25.jar!/META-INF/"
 1 = {java.net.URL@4039} "jar:file:/data/servers/apache-tomcat-9.0.24/webapps/test-jsf-primefaces-0.1.0.BUILD-SNAPSHOT/WEB-INF/lib/myfaces-api-2.2.12.jar!/META-INF/"
 2 = {java.net.URL@4040} "jar:file:/data/servers/apache-tomcat-9.0.24/webapps/test-jsf-primefaces-0.1.0.BUILD-SNAPSHOT/WEB-INF/lib/logback-core-1.2.3.jar!/META-INF/"
 3 = {java.net.URL@4041} "jar:file:/data/servers/apache-tomcat-9.0.24/webapps/test-jsf-primefaces-0.1.0.BUILD-SNAPSHOT/WEB-INF/lib/commons-beanutils-1.9.3.jar!/META-INF/"
 4 = {java.net.URL@4042} "jar:file:/data/servers/apache-tomcat-9.0.24/webapps/test-jsf-primefaces-0.1.0.BUILD-SNAPSHOT/WEB-INF/lib/logback-classic-1.2.3.jar!/META-INF/"
 5 = {java.net.URL@4043} "jar:file:/data/servers/apache-tomcat-9.0.24/webapps/test-jsf-primefaces-0.1.0.BUILD-SNAPSHOT/WEB-INF/lib/myfaces-impl-2.2.12.jar!/META-INF/"
 6 = {java.net.URL@4044} "jar:file:/data/servers/apache-tomcat-9.0.24/webapps/test-jsf-primefaces-0.1.0.BUILD-SNAPSHOT/WEB-INF/lib/primefaces-7.0.jar!/META-INF/"
 7 = {java.net.URL@4045} "jar:file:/data/servers/apache-tomcat-9.0.24/webapps/test-jsf-primefaces-0.1.0.BUILD-SNAPSHOT/WEB-INF/lib/slf4j-api-1.7.25.jar!/META-INF/"
 8 = {java.net.URL@4046} "jar:file:/data/servers/apache-tomcat-9.0.24/webapps/test-jsf-primefaces-0.1.0.BUILD-SNAPSHOT/WEB-INF/lib/commons-digester-1.8.jar!/META-INF/"
 9 = {java.net.URL@4047} "jar:file:/data/servers/apache-tomcat-9.0.24/webapps/test-jsf-primefaces-0.1.0.BUILD-SNAPSHOT/WEB-INF/lib/jcl-over-slf4j-1.7.25.jar!/META-INF/"
10 = {java.net.URL@4048} "jar:file:/data/servers/apache-tomcat-9.0.24/webapps/test-jsf-primefaces-0.1.0.BUILD-SNAPSHOT/WEB-INF/lib/commons-collections-3.2.2.jar!/META-INF/"
```

In pax-web:

```
  0 = {java.net.URL@11262} "bundle://101.4:2/META-INF/"
  1 = {java.net.URL@11263} "bundle://101.4:3/META-INF/"
  2 = {java.net.URL@11264} "bundle://101.4:4/META-INF/"
  3 = {java.net.URL@11265} "bundle://101.4:5/META-INF/"
  4 = {java.net.URL@11266} "bundle://101.4:6/META-INF/"
  5 = {java.net.URL@11267} "bundle://101.4:7/META-INF/"
  6 = {java.net.URL@11268} "bundle://101.4:8/META-INF/"
  7 = {java.net.URL@11269} "bundle://101.4:9/META-INF/"
  8 = {java.net.URL@11270} "bundle://101.4:10/META-INF/"
  9 = {java.net.URL@11271} "bundle://101.4:11/META-INF/"
 10 = {java.net.URL@11272} "bundle://101.4:12/META-INF/"
 11 = {java.net.URL@11273} "bundle://101.4:13/META-INF/"
 12 = {java.net.URL@11274} "bundle://45.0:1/META-INF/"
 13 = {java.net.URL@11275} "bundle://6.0:1/META-INF/"
 14 = {java.net.URL@11276} "bundle://46.0:1/META-INF/"
 15 = {java.net.URL@11277} "bundle://96.0:1/META-INF/"
 16 = {java.net.URL@11278} "bundle://44.0:1/META-INF/"
 17 = {java.net.URL@11279} "bundle://102.0:1/META-INF/"
 18 = {java.net.URL@11280} "bundle://3.0:1/META-INF/"
 19 = {java.net.URL@11281} "bundle://9.0:1/META-INF/"
 20 = {java.net.URL@11282} "bundle://2.0:1/META-INF/"
 21 = {java.net.URL@11283} "bundle://8.0:1/META-INF/"
 22 = {java.net.URL@11284} "bundle://90.0:1/META-INF/"
 23 = {java.net.URL@11285} "bundle://98.0:1/META-INF/"
 24 = {java.net.URL@11286} "bundle://58.0:1/META-INF/"
 25 = {java.net.URL@11287} "bundle://57.0:1/META-INF/"
 26 = {java.net.URL@11288} "bundle://56.0:1/META-INF/"
 27 = {java.net.URL@11289} "bundle://86.0:1/META-INF/"
 28 = {java.net.URL@11290} "bundle://87.0:1/META-INF/"
 29 = {java.net.URL@11291} "bundle://88.0:1/META-INF/"
 30 = {java.net.URL@11292} "bundle://103.0:1/META-INF/"
```

In Tomcat, `java.net.URL#openConnection()` returns instance of `sun.net.www.protocol.jar.JarURLConnection`, In pax-web it's instance of `org.apache.felix.framework.URLHandlersBundleURLConnection`

That's enough to break the process in pax-web...

Because in Tomcat, the classloader is `org.apache.catalina.loader.ParallelWebappClassLoader` and in pax-web it's `org.ops4j.pax.web.service.spi.util.ResourceDelegatingBundleClassLoader` there's some change that we can fix this at pax-web level.

But I'm not yet sure.

---

**Affects:** 7.2.12
Votes: 0, Watches: 1

**Comment by grgrzybek** [comment]
TLDs are parsed correctly in Pax Web 8. As well as SCIs and facelet libraries.
