### ISSUE TITLE
myfaces-impl thinks it's running inside Tomcat

### ISSUE THREAD

**Issue by grgrzybek** [ops4j/org.ops4j.pax.web#1604]
When discovering injection providers, TCCL looks like this:
```
TCCL:
result = {org.ops4j.pax.web.service.spi.servlet.OsgiServletContextClassLoader@7034} 
 bundles: java.util.List  = {java.util.Collections$UnmodifiableRandomAccessList@7042}  size = 5
  0 = {org.apache.felix.framework.BundleImpl@7059} "org.ops4j.pax.web.samples.war-jsf23-embedded [46]"
  1 = {org.apache.felix.framework.BundleImpl@7060} "org.ops4j.pax.web.pax-web-tomcat-common [35]"
  2 = {org.apache.felix.framework.BundleImpl@7061} "org.ops4j.pax.web.pax-web-jsp [37]"
  3 = {org.apache.felix.framework.BundleImpl@7062} "javax.websocket-api [38]"
  4 = {org.apache.felix.framework.BundleImpl@7063} "org.ops4j.pax.web.pax-web-jetty [24]"
```

`pax-web-tomcat-common` exposes `org.apache.tomcat.InstanceManager`, but later, this class is tried to be loaded by BundleClassLoader of the WAB itself, leading to:
```
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_282]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_282]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_282]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_282]
	at javax.faces.FactoryFinder.injectAndPostConstruct(FactoryFinder.java:420) ~[war:?]
	at javax.faces.FactoryFinder.newFactoryInstance(FactoryFinder.java:524) ~[war:?]
	at javax.faces.FactoryFinder._getFactory(FactoryFinder.java:366) ~[war:?]
	at javax.faces.FactoryFinder.getFactory(FactoryFinder.java:230) ~[war:?]
	at org.apache.myfaces.application.ViewHandlerImpl.<init>(ViewHandlerImpl.java:93) ~[war:?]
	at org.apache.myfaces.application.ApplicationImpl.<init>(ApplicationImpl.java:302) ~[war:?]
	at org.apache.myfaces.application.ApplicationImpl.<init>(ApplicationImpl.java:285) ~[war:?]
	at org.apache.myfaces.application.ApplicationFactoryImpl.createAndLogNewApplication(ApplicationFactoryImpl.java:54) ~[war:?]
	at org.apache.myfaces.application.ApplicationFactoryImpl.<init>(ApplicationFactoryImpl.java:49) ~[war:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_282]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_282]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_282]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_282]
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_282]
	at javax.faces.FactoryFinder.newFactoryInstance(FactoryFinder.java:523) ~[war:?]
	at javax.faces.FactoryFinder._getFactory(FactoryFinder.java:366) ~[war:?]
	at javax.faces.FactoryFinder.getFactory(FactoryFinder.java:230) ~[war:?]
	at org.apache.myfaces.config.FacesConfigurator.configureApplication(FacesConfigurator.java:710) ~[war:?]
	at org.apache.myfaces.config.FacesConfigurator.configure(FacesConfigurator.java:606) ~[war:?]
	at org.apache.myfaces.webapp.AbstractFacesInitializer.buildConfiguration(AbstractFacesInitializer.java:456) ~[war:?]
	at org.apache.myfaces.webapp.Jsp21FacesInitializer.initContainerIntegration(Jsp21FacesInitializer.java:70) ~[war:?]
	at org.apache.myfaces.webapp.AbstractFacesInitializer.initFaces(AbstractFacesInitializer.java:190) ~[war:?]
	at org.apache.myfaces.webapp.StartupServletContextListener.contextInitialized(StartupServletContextListener.java:103) ~[war:?]
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:1068) ~[9.4.40.v20210413:9.4.40.v20210413]
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:572) ~[9.4.40.v20210413:9.4.40.v20210413]
	at org.ops4j.pax.web.service.jetty.internal.PaxWebServletContextHandler.callContextInitialized(PaxWebServletContextHandler.java:104) ~[8.0.0-SNAPSHOT:?]
	at org.eclipse.jetty.server.handler.ContextHandler.contextInitialized(ContextHandler.java:997) ~[9.4.40.v20210413:9.4.40.v20210413]
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:746) ~[9.4.40.v20210413:9.4.40.v20210413]
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:379) ~[9.4.40.v20210413:9.4.40.v20210413]
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:911) ~[9.4.40.v20210413:9.4.40.v20210413]
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:288) ~[9.4.40.v20210413:9.4.40.v20210413]
	at org.ops4j.pax.web.service.jetty.internal.PaxWebServletContextHandler.doStart(PaxWebServletContextHandler.java:188) ~[8.0.0-SNAPSHOT:?]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73) ~[?:?]
	at org.ops4j.pax.web.service.jetty.internal.JettyServerWrapper.ensureServletContextStarted(JettyServerWrapper.java:1593) ~[8.0.0-SNAPSHOT:?]
	at org.ops4j.pax.web.service.jetty.internal.JettyServerWrapper.visit(JettyServerWrapper.java:665) ~[8.0.0-SNAPSHOT:?]
	at org.ops4j.pax.web.service.spi.task.TransactionStateChange.accept(TransactionStateChange.java:35) ~[8.0.0-SNAPSHOT:?]
	at org.ops4j.pax.web.service.spi.task.Batch.accept(Batch.java:381) ~[8.0.0-SNAPSHOT:?]
	at org.ops4j.pax.web.service.jetty.internal.JettyServerController.sendBatch(JettyServerController.java:168) ~[8.0.0-SNAPSHOT:?]
	at org.ops4j.pax.web.service.internal.HttpServiceEnabled$WebAppWebContainer.lambda$sendBatch$0(HttpServiceEnabled.java:1877) ~[?:?]
	at org.ops4j.pax.web.service.spi.model.ServerModel.lambda$run$2(ServerModel.java:441) ~[8.0.0-SNAPSHOT:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604) [?:1.8.0_282]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_282]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_282]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_282]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_282]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_282]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_282]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
Caused by: java.lang.NoClassDefFoundError: org/apache/tomcat/InstanceManager
	at org.apache.myfaces.spi.impl.Tomcat7AnnotationInjectionProvider.initManager(Tomcat7AnnotationInjectionProvider.java:182) ~[war:?]
	at org.apache.myfaces.spi.impl.Tomcat7AnnotationInjectionProvider.postConstruct(Tomcat7AnnotationInjectionProvider.java:85) ~[war:?]
	... 52 more
Caused by: java.lang.ClassNotFoundException: org.apache.tomcat.InstanceManager not found by org.ops4j.pax.web.samples.war-jsf23-embedded [46]
	at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1639) ~[?:?]
	at org.apache.felix.framework.BundleWiringImpl.access$200(BundleWiringImpl.java:80) ~[?:?]
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:2053) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_282]
	at org.apache.myfaces.spi.impl.Tomcat7AnnotationInjectionProvider.initManager(Tomcat7AnnotationInjectionProvider.java:182) ~[war:?]
	at org.apache.myfaces.spi.impl.Tomcat7AnnotationInjectionProvider.postConstruct(Tomcat7AnnotationInjectionProvider.java:85) ~[war:?]
	... 52 more
```

The solution is to add `Import-Package: org.apache.tomcat` to the WAB, but it should be handled better.

**Comment by grgrzybek** [comment]
Works fine on Jetty and Undertow - simply `org.apache.tomcat.SimpleInstanceManager` is found (as configured by pax-web-jsp).
