### ISSUE TITLE
upgrade to ASM 9.2 so that pax-web can work with JDK18-EA

### ISSUE THREAD

**Issue by ffang** [ops4j/org.ops4j.pax.web#1630]
to aovid the error like from ASM ClassReader
```
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 62
		at org.objectweb.asm.ClassReader.<init>(ClassReader.java:196)
		at org.objectweb.asm.ClassReader.<init>(ClassReader.java:177)
		at org.objectweb.asm.ClassReader.<init>(ClassReader.java:163)
		at org.objectweb.asm.ClassReader.<init>(ClassReader.java:284)
```
Class file major version 62 stands for JDK18, and ASM 9.2 starts supporting this version

**Comment by jbonofre** [comment]
Yeah it makes sense. I will do it. I will double check in karaf as well.
