### ISSUE TITLE
pax-web-undertow ResourceServlet fails when requests are wrapped

### ISSUE THREAD

**Issue by grgrzybek** [ops4j/org.ops4j.pax.web#1634]
The exception is:
```
Caused by: java.lang.IllegalStateException: Request is not an instance of io.undertow.servlet.spec.HttpServletRequestImpl
	at org.ops4j.pax.web.service.undertow.internal.ResourceServlet.service(ResourceServlet.java:72)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:750) ~[!/:4.0.1]
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
...
```

**Comment by grgrzybek** [comment]
It doesn't affect Pax Web 8, because resource management is completely rewritten.
