### ISSUE TITLE
Some problems when refreshing Pax Web bundles when some WABs are installed/deployed

### ISSUE THREAD

**Issue by grgrzybek** [ops4j/org.ops4j.pax.web#1646]
Like this one:
```
2021-11-17T14:23:02,650 | ERROR | wab-extender-7-thread-1 | BundleWebApplication             | 75 - org.ops4j.pax.web.pax-web-extender-war - 8.0.1.SNAPSHOT | Problem processing Web Application "/war-jsf23-embedded" for bundle org.ops4j.pax.web.samples.war-jsf23-embedded/8.0.1.SNAPSHOT: null
java.lang.NullPointerException: null
	at org.ops4j.pax.web.extender.war.internal.model.BundleWebApplication.deploy(BundleWebApplication.java:703) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_312]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_312]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_312]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_312]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_312]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_312]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
```

**Comment by grgrzybek** [comment]
Reproduced with `WarBasicAuthSecuredIntegrationTest` test. Also I see:
```
14:41:04.486 [HttpService->WarExtender (remove HttpService)] WARN  (ServerModel.java:574) org.ops4j.pax.web.service.spi.model.ServerModel - Problem incrementing the change counter: The service registration is no longer valid.
14:41:04.486 [paxweb-config-1-thread-1 (change config)] WARN  (ServerModel.java:574) org.ops4j.pax.web.service.spi.model.ServerModel - Problem incrementing the change counter: The service registration is no longer valid.
```
