### ISSUE TITLE
Installing pax-web-war 8.0.1 on Karaf 4.3.6 throws ClassNotFoundException: org.ops4j.pax.web.service.spi.Configuration

### ISSUE THREAD

**Issue by mefernandez** [ops4j/org.ops4j.pax.web#1700]
I installed pax-web-features 8.0.1 on a clean Karaf 4.3.6.

```
karaf@root()> feature:repo-add mvn:org.ops4j.pax.web/pax-web-features/8.0.1/xml/features                                                                                                    
Adding feature url mvn:org.ops4j.pax.web/pax-web-features/8.0.1/xml/features
```

Then I try:
```
feature:install pax-web-war
```

Which prints a long stacktrace, the gist of it being:
```
Caused by: java.lang.ClassNotFoundException: org.ops4j.pax.web.service.spi.Configuration not found by org.ops4j.pax.web.pax-web-spi
```

Can I help?

**Comment by grgrzybek** [comment]
Please show full stack trace. This is strange because `org.ops4j.pax.web.pax-web-spi` (symbolic name) is THE bundle that _contains_ `Configuration` class. However in Pax Web 8 it was moved to `org.ops4j.pax.web.service.spi.config` package. So we have to track down what is expecting the old package.

**Comment by mefernandez** [comment]
Hi Grzegorz,

This is the full stack trace:

```
karaf-instance-1_1    | org.apache.karaf.features.internal.util.MultiException: Error restarting bundles:
karaf-instance-1_1    | 	Activator start error in bundle org.ops4j.pax.web.pax-web-extender-whiteboard [110].
karaf-instance-1_1    | 	Singleton conflict. Unresolved requirements: []
karaf-instance-1_1    | 	Activator start error in bundle org.ops4j.pax.web.pax-web-extender-war [109].
karaf-instance-1_1    | 	Activator start error in bundle org.ops4j.pax.web.pax-web-runtime [113].
karaf-instance-1_1    | 	at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:1049)
karaf-instance-1_1    | 	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1069)
karaf-instance-1_1    | 	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.lambda$doProvisionInThread$13(FeaturesServiceImpl.java:1004)
karaf-instance-1_1    | 	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
karaf-instance-1_1    | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
karaf-instance-1_1    | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
karaf-instance-1_1    | 	at java.base/java.lang.Thread.run(Unknown Source)
karaf-instance-1_1    | 	Suppressed: org.osgi.framework.BundleException: Activator start error in bundle org.ops4j.pax.web.pax-web-extender-whiteboard [110].
karaf-instance-1_1    | 		at org.apache.felix.framework.Felix.activateBundle(Felix.java:2452)
karaf-instance-1_1    | 		at org.apache.felix.framework.Felix.startBundle(Felix.java:2308)
karaf-instance-1_1    | 		at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:998)
karaf-instance-1_1    | 		at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:984)
karaf-instance-1_1    | 		at org.apache.karaf.features.internal.service.BundleInstallSupportImpl.startBundle(BundleInstallSupportImpl.java:165)
karaf-instance-1_1    | 		at org.apache.karaf.features.internal.service.FeaturesServiceImpl.startBundle(FeaturesServiceImpl.java:1160)
karaf-instance-1_1    | 		at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:1041)
karaf-instance-1_1    | 		... 6 more
karaf-instance-1_1    | 	Caused by: java.lang.NoClassDefFoundError: org/ops4j/pax/web/service/whiteboard/WhiteboardElement
karaf-instance-1_1    | 		at org.ops4j.pax.web.extender.whiteboard.internal.Activator.trackHttpContexts(Activator.java:145)
karaf-instance-1_1    | 		at org.ops4j.pax.web.extender.whiteboard.internal.Activator.start(Activator.java:102)
karaf-instance-1_1    | 		at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:698)
karaf-instance-1_1    | 		at org.apache.felix.framework.Felix.activateBundle(Felix.java:2402)
karaf-instance-1_1    | 		... 12 more
karaf-instance-1_1    | 	Caused by: java.lang.ClassNotFoundException: org.ops4j.pax.web.service.whiteboard.WhiteboardElement not found by org.ops4j.pax.web.pax-web-api [120]
karaf-instance-1_1    | 		at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1565)
karaf-instance-1_1    | 		at org.apache.felix.framework.BundleWiringImpl.access$300(BundleWiringImpl.java:78)
karaf-instance-1_1    | 		at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1950)
karaf-instance-1_1    | 		at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
karaf-instance-1_1    | 		at org.apache.felix.framework.BundleWiringImpl.getClassByDelegation(BundleWiringImpl.java:1343)
karaf-instance-1_1    | 		at org.apache.felix.framework.BundleWiringImpl.searchImports(BundleWiringImpl.java:1586)
karaf-instance-1_1    | 		at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1516)
karaf-instance-1_1    | 		at org.apache.felix.framework.BundleWiringImpl.access$300(BundleWiringImpl.java:78)
karaf-instance-1_1    | 		at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1950)
karaf-instance-1_1    | 		at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
karaf-instance-1_1    | 		... 16 more
karaf-instance-1_1    | 	Suppressed: org.osgi.framework.BundleException: Singleton conflict. Unresolved requirements: []
karaf-instance-1_1    | 		at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4368)
karaf-instance-1_1    | 		at org.apache.felix.framework.Felix.startBundle(Felix.java:2281)
karaf-instance-1_1    | 		at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:998)
karaf-instance-1_1    | 		at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:984)
karaf-instance-1_1    | 		at org.apache.karaf.features.internal.service.BundleInstallSupportImpl.startBundle(BundleInstallSupportImpl.java:165)
karaf-instance-1_1    | 		at org.apache.karaf.features.internal.service.FeaturesServiceImpl.startBundle(FeaturesServiceImpl.java:1160)
karaf-instance-1_1    | 		at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:1041)
karaf-instance-1_1    | 		... 6 more
karaf-instance-1_1    | 	Suppressed: org.osgi.framework.BundleException: Activator start error in bundle org.ops4j.pax.web.pax-web-extender-war [109].
karaf-instance-1_1    | 		at org.apache.felix.framework.Felix.activateBundle(Felix.java:2452)
karaf-instance-1_1    | 		at org.apache.felix.framework.Felix.startBundle(Felix.java:2308)
karaf-instance-1_1    | 		at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:998)
karaf-instance-1_1    | 		at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:984)
karaf-instance-1_1    | 		at org.apache.karaf.features.internal.service.BundleInstallSupportImpl.startBundle(BundleInstallSupportImpl.java:165)
karaf-instance-1_1    | 		at org.apache.karaf.features.internal.service.FeaturesServiceImpl.startBundle(FeaturesServiceImpl.java:1160)
karaf-instance-1_1    | 		at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:1041)
karaf-instance-1_1    | 		... 6 more
karaf-instance-1_1    | 	Caused by: java.lang.NoClassDefFoundError: org/ops4j/pax/web/service/spi/WebListener
karaf-instance-1_1    | 		at java.base/java.lang.ClassLoader.defineClass1(Native Method)
karaf-instance-1_1    | 		at java.base/java.lang.ClassLoader.defineClass(Unknown Source)
karaf-instance-1_1    | 		at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.defineClass(BundleWiringImpl.java:2312)
karaf-instance-1_1    | 		at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.defineClassParallel(BundleWiringImpl.java:2130)
karaf-instance-1_1    | 		at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.findClass(BundleWiringImpl.java:2064)
karaf-instance-1_1    | 		at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1533)
karaf-instance-1_1    | 		at org.apache.felix.framework.BundleWiringImpl.access$300(BundleWiringImpl.java:78)
karaf-instance-1_1    | 		at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1950)
karaf-instance-1_1    | 		at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
karaf-instance-1_1    | 		at org.ops4j.pax.web.extender.war.internal.Activator.doStart(Activator.java:47)
karaf-instance-1_1    | 		at org.ops4j.pax.web.extender.war.internal.extender.AbstractExtender.start(AbstractExtender.java:117)
karaf-instance-1_1    | 		at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:698)
karaf-instance-1_1    | 		at org.apache.felix.framework.Felix.activateBundle(Felix.java:2402)
karaf-instance-1_1    | 		... 12 more
karaf-instance-1_1    | 	Caused by: java.lang.ClassNotFoundException: org.ops4j.pax.web.service.spi.WebListener not found by org.ops4j.pax.web.pax-web-spi [123]
karaf-instance-1_1    | 		at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1565)
karaf-instance-1_1    | 		at org.apache.felix.framework.BundleWiringImpl.access$300(BundleWiringImpl.java:78)
karaf-instance-1_1    | 		at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1950)
karaf-instance-1_1    | 		at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
karaf-instance-1_1    | 		at org.apache.felix.framework.BundleWiringImpl.getClassByDelegation(BundleWiringImpl.java:1343)
karaf-instance-1_1    | 		at org.apache.felix.framework.BundleWiringImpl.searchImports(BundleWiringImpl.java:1586)
karaf-instance-1_1    | 		at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1516)
karaf-instance-1_1    | 		at org.apache.felix.framework.BundleWiringImpl.access$300(BundleWiringImpl.java:78)
karaf-instance-1_1    | 		at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1950)
karaf-instance-1_1    | 		at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
karaf-instance-1_1    | 		... 25 more
karaf-instance-1_1    | 	Suppressed: org.osgi.framework.BundleException: Activator start error in bundle org.ops4j.pax.web.pax-web-runtime [113].
karaf-instance-1_1    | 		at org.apache.felix.framework.Felix.activateBundle(Felix.java:2452)
karaf-instance-1_1    | 		at org.apache.felix.framework.Felix.startBundle(Felix.java:2308)
karaf-instance-1_1    | 		at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:998)
karaf-instance-1_1    | 		at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:984)
karaf-instance-1_1    | 		at org.apache.karaf.features.internal.service.BundleInstallSupportImpl.startBundle(BundleInstallSupportImpl.java:165)
karaf-instance-1_1    | 		at org.apache.karaf.features.internal.service.FeaturesServiceImpl.startBundle(FeaturesServiceImpl.java:1160)
karaf-instance-1_1    | 		at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:1041)
karaf-instance-1_1    | 		... 6 more
karaf-instance-1_1    | 	Caused by: java.lang.NoClassDefFoundError: org/ops4j/pax/web/service/spi/Configuration
karaf-instance-1_1    | 		at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
karaf-instance-1_1    | 		at java.base/java.lang.Class.privateGetDeclaredConstructors(Unknown Source)
karaf-instance-1_1    | 		at java.base/java.lang.Class.getConstructor0(Unknown Source)
karaf-instance-1_1    | 		at java.base/java.lang.Class.newInstance(Unknown Source)
karaf-instance-1_1    | 		at org.apache.felix.framework.Felix.createBundleActivator(Felix.java:4750)
karaf-instance-1_1    | 		at org.apache.felix.framework.Felix.activateBundle(Felix.java:2383)
karaf-instance-1_1    | 		... 12 more
karaf-instance-1_1    | 	Caused by: java.lang.ClassNotFoundException: org.ops4j.pax.web.service.spi.Configuration not found by org.ops4j.pax.web.pax-web-spi [123]
karaf-instance-1_1    | 		at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1565)
karaf-instance-1_1    | 		at org.apache.felix.framework.BundleWiringImpl.access$300(BundleWiringImpl.java:78)
karaf-instance-1_1    | 		at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1950)
karaf-instance-1_1    | 		at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
karaf-instance-1_1    | 		at org.apache.felix.framework.BundleWiringImpl.getClassByDelegation(BundleWiringImpl.java:1343)
karaf-instance-1_1    | 		at org.apache.felix.framework.BundleWiringImpl.searchImports(BundleWiringImpl.java:1586)
karaf-instance-1_1    | 		at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1516)
karaf-instance-1_1    | 		at org.apache.felix.framework.BundleWiringImpl.access$300(BundleWiringImpl.java:78)
karaf-instance-1_1    | 		at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1950)
karaf-instance-1_1    | 		at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
karaf-instance-1_1    | 		... 18 more
```

**Comment by grgrzybek** [comment]
`Singleton conflict. Unresolved requirements: []` confirms my theory - you have both pax web 8.0.1 and 7.3.x used by default by Karaf 4.3.6.
Please start with `repo-list`, you'll see:
```
karaf@root()> repo-list 
Repository                        │ URL
──────────────────────────────────┼─────────────────────────────────────────────────────────────────────────────────────────────
pax-jms-1.1.0                     │ mvn:org.ops4j.pax.jms/pax-jms-features/1.1.0/xml/features
framework-4.3.6                   │ mvn:org.apache.karaf.features/framework/4.3.6/xml/features
specs-4.3.6                       │ mvn:org.apache.karaf.features/specs/4.3.6/xml/features
org.ops4j.pax.jdbc-1.5.0          │ mvn:org.ops4j.pax.jdbc/pax-jdbc-features/1.5.0/xml/features
aries-jpa-2.7.3                   │ mvn:org.apache.aries.jpa/jpa-features/2.7.3/xml/features
pax-transx-0.5.0                  │ mvn:org.ops4j.pax.transx/pax-transx-features/0.5.0/xml/features
openjpa-3.2.0                     │ mvn:org.apache.openjpa/openjpa-features/3.2.0/xml/features
org.ops4j.pax.web-7.3.23          │ mvn:org.ops4j.pax.web/pax-web-features/7.3.23/xml/features
hibernate-validator-osgi-features │ mvn:org.hibernate.validator/hibernate-validator-osgi-karaf-features/7.0.1.Final/xml/features
standard-4.3.6                    │ mvn:org.apache.karaf.features/standard/4.3.6/xml/features
enterprise-4.3.6                  │ mvn:org.apache.karaf.features/enterprise/4.3.6/xml/features
spring-4.3.6                      │ mvn:org.apache.karaf.features/spring/4.3.6/xml/features
org.ops4j.pax.cdi-1.1.4           │ mvn:org.ops4j.pax.cdi/pax-cdi-features/1.1.4/xml/features
```

please remove old pax web:
```
karaf@root()> repo-remove org.ops4j.pax.web-7.3.23
Removing features repository: mvn:org.ops4j.pax.web/pax-web-features/7.3.23/xml/features
```

Add new one:
```
karaf@root()> repo-add mvn:org.ops4j.pax.web/pax-web-features/8.0.1/xml/features
Adding feature url mvn:org.ops4j.pax.web/pax-web-features/8.0.1/xml/features
```

Then you can see pax web 8.0.1 features:
```
karaf@root()> feature:list | grep pax-web
pax-web-core                      │ 7.3.23           │          │ Uninstalled │ org.ops4j.pax.web-7.3.23          │ Provide Core pax-web bundles
pax-web-http                      │ 7.3.23           │          │ Uninstalled │ standard-4.3.6                    │ Pax Web OSGi HTTP Service
pax-web-http-whiteboard           │ 7.3.23           │          │ Uninstalled │ standard-4.3.6                    │ Pax Web OSGi HTTP Whiteboard support
pax-web-war                       │ 4.3.6            │          │ Uninstalled │ standard-4.3.6                    │ Turn Karaf as a full WebContainer
pax-web-specs                     │ 8.0.1            │          │ Uninstalled │ org.ops4j.pax.web-8.0.1           │ Jakarta web APIs and related bundle fragments add
pax-web-core                      │ 8.0.1            │          │ Uninstalled │ org.ops4j.pax.web-8.0.1           │ Core Pax Web bundles
pax-web-websockets                │ 8.0.1            │          │ Uninstalled │ org.ops4j.pax.web-8.0.1           │ Pax Web bundles for Web Sockets (JSR 356) support
pax-web-jetty                     │ 9.4.45.v20220203 │          │ Uninstalled │ org.ops4j.pax.web-8.0.1           │ Jetty 9 bundles
pax-web-jetty-websockets          │ 9.4.45.v20220203 │          │ Uninstalled │ org.ops4j.pax.web-8.0.1           │ Jetty 9 bundles for Web Sockets support
pax-web-http-jetty                │ 8.0.1            │          │ Uninstalled │ org.ops4j.pax.web-8.0.1           │ Http Service implementation using Jetty 9
pax-web-tomcat                    │ 9.0.58           │          │ Uninstalled │ org.ops4j.pax.web-8.0.1           │ Tomcat 9 bundles
pax-web-tomcat-websockets         │ 9.0.58           │          │ Uninstalled │ org.ops4j.pax.web-8.0.1           │ Tomcat 9 bundles for Web Sockets support
pax-web-http-tomcat               │ 8.0.1            │          │ Uninstalled │ org.ops4j.pax.web-8.0.1           │ Http Service implementation using Tomcat 9
pax-web-undertow                  │ 2.2.15.Final     │          │ Uninstalled │ org.ops4j.pax.web-8.0.1           │ Undertow 2 bundles
pax-web-undertow-websockets       │ 2.2.15.Final     │          │ Uninstalled │ org.ops4j.pax.web-8.0.1           │ Undertow 2 bundles for Web Sockets support
pax-web-http-undertow             │ 8.0.1            │          │ Uninstalled │ org.ops4j.pax.web-8.0.1           │ Http Service implementation using Undertow 2
pax-web-jsp                       │ 8.0.1            │          │ Uninstalled │ org.ops4j.pax.web-8.0.1           │
pax-web-whiteboard                │ 8.0.1            │          │ Uninstalled │ org.ops4j.pax.web-8.0.1           │ Whiteboard Service implementation
pax-web-war                       │ 8.0.1            │          │ Uninstalled │ org.ops4j.pax.web-8.0.1           │ Web Applications implementation
pax-web-karaf                     │ 8.0.1            │          │ Uninstalled │ org.ops4j.pax.web-8.0.1           │ Pax Web Karaf integration
```

And install the Jetty ones (I'm going to document everything in https://issues.apache.org/jira/browse/KARAF-7406):
```
karaf@root()> feature:install pax-web-jetty pax-web-whiteboard pax-web-war pax-web-karaf
```

You'll get only Jetty bundles. Pax Web is an implementation of 3 OSGi CMPN Web-related specs:
* pax-web-http-jetty/pax-web-http-tomcat/pax-web-http-undertow - core implementation of chapter 102 (Http Service) - always required - you have to choose one
* pax-web-whiteboard - implementation of chapter 140 (Whiteboard) - needs one of the above, but it's not container-specific by itself
* pax-web-war - implementation of chapter 128 (Web Applications / WABs) - also not container-specific

Mind that feature names `pax-web-http` and `pax-web-http-whiteboard` are Karaf-specific - they use Pax Web as dependencies and just give you different names.
Pax Web 8 renamed some of the features to make them more consistent.

Additionally `pax-web-karaf` features adds you some new cool (IMO) Karaf commands that show much more information (see https://ggrzybek.blogspot.com/2021/11/pax-web-8-whiteboard-services-and-karaf.html)

**Comment by mefernandez** [comment]
Thanks for your prompt help Grzegorz.
