### ISSUE TITLE
org.eclipse.jetty.rewrite.handler.RewriteHandler cannot be found in Karaf 4.4.0

### ISSUE THREAD

**Issue by annorchen** [ops4j/org.ops4j.pax.web#1712]
We use org.eclipse.jetty.rewrite.handler.RewriteHandler in our jetty.xml in Karaf Server.
```xml
    <Get name="handler">
		<Call name="addHandler">
		  <Arg>
			<New id="Contexts" class="org.eclipse.jetty.server.handler.ContextHandlerCollection"/>
		  </Arg>
		</Call>

	    <!-- Configure jetty webserver to redirect root webpage access to dashboard ... -->
	    <!--redirect root page to /home as default -->
		<Call name="addHandler">
		  <Arg>
			<New id="Rewrite" class="org.eclipse.jetty.rewrite.handler.RewriteHandler">
			  <Set name="rewriteRequestURI">true</Set>
			  <Set name="rewritePathInfo">false</Set>
			  <Set name="originalPathAttribute">requestedPath</Set>
			  <Call name="addRule">
				<Arg>
				  <New class="org.eclipse.jetty.rewrite.handler.RedirectRegexRule">
				<Set name="regex">^/$</Set>
				<Set name="replacement">/home</Set>
				  </New>
				</Arg>
			  </Call>
			</New>
		  </Arg>
		</Call>

	</Get>
```

 Since we update to new Karaf 4.4.0, we got this Exception below:
I found out, that this dependency has commted out, maybe this cause the issue?
https://github.com/ops4j/org.ops4j.pax.web/blob/main/pax-web-features/src/main/resources/features.xml
And this old issue: https://github.com/ops4j/org.ops4j.pax.web/issues/1285

**Exception:**
```
2022-04-25T18:24:21,673 | WARN  | thread-1 (change controller) | org.ops4j.pax.web.service.jetty.internal.JettyServerWrapper      | Problem parsing file:///D:/_DEV/karaf_server/etc/jetty.xml: org.eclipse.jetty.rewrite.handler.RewriteHandler cannot be found by org.ops4j.pax.web.pax-web-jetty_8.0.2
java.lang.ClassNotFoundException: org.eclipse.jetty.rewrite.handler.RewriteHandler cannot be found by org.ops4j.pax.web.pax-web-jetty_8.0.2
	at org.eclipse.osgi.internal.loader.BundleLoader.generateException(BundleLoader.java:529) ~[?:?]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass0(BundleLoader.java:524) ~[?:?]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:416) ~[?:?]
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:168) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	at org.eclipse.jetty.util.Loader.loadClass(Loader.java:64) ~[bundleFile:9.4.46.v20220331]
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.newObj(XmlConfiguration.java:1006) ~[bundleFile:9.4.46.v20220331]
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.itemValue(XmlConfiguration.java:1540) ~[bundleFile:9.4.46.v20220331]
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.value(XmlConfiguration.java:1441) ~[bundleFile:9.4.46.v20220331]
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.access$700(XmlConfiguration.java:395) ~[bundleFile:9.4.46.v20220331]
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration$Args.<init>(XmlConfiguration.java:1699) ~[bundleFile:9.4.46.v20220331]
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration$Args.<init>(XmlConfiguration.java:1686) ~[bundleFile:9.4.46.v20220331]
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.call(XmlConfiguration.java:942) ~[bundleFile:9.4.46.v20220331]
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:515) ~[bundleFile:9.4.46.v20220331]
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.get(XmlConfiguration.java:886) ~[bundleFile:9.4.46.v20220331]
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:518) ~[bundleFile:9.4.46.v20220331]
	at org.eclipse.jetty.xml.XmlConfiguration$JettyXmlConfiguration.configure(XmlConfiguration.java:468) ~[bundleFile:9.4.46.v20220331]
	at org.eclipse.jetty.xml.XmlConfiguration.configure(XmlConfiguration.java:380) ~[bundleFile:9.4.46.v20220331]
	at org.ops4j.pax.web.service.jetty.internal.JettyServerWrapper.processConfiguration(JettyServerWrapper.java:2455) ~[bundleFile:?]
	at org.ops4j.pax.web.service.jetty.internal.JettyServerWrapper.applyJettyConfiguration(JettyServerWrapper.java:413) ~[bundleFile:?]
	at org.ops4j.pax.web.service.jetty.internal.JettyServerWrapper.configure(JettyServerWrapper.java:267) ~[bundleFile:?]
	at org.ops4j.pax.web.service.jetty.internal.JettyServerController.configure(JettyServerController.java:95) ~[bundleFile:?]
	at org.ops4j.pax.web.service.internal.Activator.performConfiguration(Activator.java:548) ~[?:?]
	at org.ops4j.pax.web.service.internal.Activator.updateController(Activator.java:441) ~[?:?]
	at org.ops4j.pax.web.service.internal.Activator.lambda$updateServerControllerFactory$1(Activator.java:347) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```

**Comment by grgrzybek** [comment]
Thanks for the report.
Because Pax Web 8 was almost complete rewrite of Pax Web 7, I had to start somewhere and my approach was to disable/comment everything and work consecutively on the parts I uncomment/enable until all existing (and many new) tests start working.

Indeed, I've commented out several Jetty bundles (for example we definitely don't want jetty-webapp, as Pax Web itself implements the WAR/WAB handling). I simply missed jetty-rewrite.

Before I start working on it (I plan to release 8.0.3 quite soon) could you please install jetty-rewrite as a bundle to check if your scenario works? At first glance I think something has to be changed so pax-web-jetty when configured sees jetty-rewrite bundle.

**Comment by grgrzybek** [comment]
I've added `pax-web-jetty-extras` feature - so far with jetty-rewrite and jetty-servlets bundles. If there's a need we can include more Jetty bundles, but these (plus, jndi, webapp, deploy) are not supposed to work well with Pax Web, because these areas are implemented differently.

jetty-jaspi will be handled with #1640 .
