### ISSUE TITLE
Build failure in war-vaadin20-spring

### ISSUE THREAD

**Issue by grgrzybek** [ops4j/org.ops4j.pax.web#1719]
The failure is related to OpenSSL / node / frontend-maven-plugin issues:
```
[ERROR] Failed to execute goal com.vaadin:vaadin-maven-plugin:20.0.6:build-frontend (default) on project war-vaadin20-spring: Execution default of goal com.vaadin:vaadin-maven-plugin:20.0.6:build-frontend failed: Webpack process exited with non-zero exit code.
[ERROR] Stderr: 'Error: error:0308010C:digital envelope routines::unsupported
[ERROR]     at new Hash (node:internal/crypto/hash:67:19)
[ERROR]     at Object.createHash (node:crypto:130:10)
[ERROR]     at module.exports (/data/sources/github.com/ops4j/org.ops4j.pax.web/samples/samples-war/war-vaadin20-spring/node_modules/.pnpm/webpack@4.46.0_webpack-cli@3.3.12/node_modules/webpack/lib/util/createHash.js:135:53)
[ERROR]     at NormalModule._initBuildHash (/data/sources/github.com/ops4j/org.ops4j.pax.web/samples/samples-war/war-vaadin20-spring/node_modules/.pnpm/webpack@4.46.0_webpack-cli@3.3.12/node_modules/webpack/lib/NormalModule.js:417:16)
[ERROR]     at handleParseError (/data/sources/github.com/ops4j/org.ops4j.pax.web/samples/samples-war/war-vaadin20-spring/node_modules/.pnpm/webpack@4.46.0_webpack-cli@3.3.12/node_modules/webpack/lib/NormalModule.js:471:10)
[ERROR]     at /data/sources/github.com/ops4j/org.ops4j.pax.web/samples/samples-war/war-vaadin20-spring/node_modules/.pnpm/webpack@4.46.0_webpack-cli@3.3.12/node_modules/webpack/lib/NormalModule.js:503:5
[ERROR]     at /data/sources/github.com/ops4j/org.ops4j.pax.web/samples/samples-war/war-vaadin20-spring/node_modules/.pnpm/webpack@4.46.0_webpack-cli@3.3.12/node_modules/webpack/lib/NormalModule.js:358:12
[ERROR]     at /data/sources/github.com/ops4j/org.ops4j.pax.web/samples/samples-war/war-vaadin20-spring/node_modules/.pnpm/loader-runner@2.4.0/node_modules/loader-runner/lib/LoaderRunner.js:373:3
[ERROR]     at iterateNormalLoaders (/data/sources/github.com/ops4j/org.ops4j.pax.web/samples/samples-war/war-vaadin20-spring/node_modules/.pnpm/loader-runner@2.4.0/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
[ERROR]     at iterateNormalLoaders (/data/sources/github.com/ops4j/org.ops4j.pax.web/samples/samples-war/war-vaadin20-spring/node_modules/.pnpm/loader-runner@2.4.0/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
[ERROR]     at /data/sources/github.com/ops4j/org.ops4j.pax.web/samples/samples-war/war-vaadin20-spring/node_modules/.pnpm/loader-runner@2.4.0/node_modules/loader-runner/lib/LoaderRunner.js:236:3
[ERROR]     at runSyncOrAsync (/data/sources/github.com/ops4j/org.ops4j.pax.web/samples/samples-war/war-vaadin20-spring/node_modules/.pnpm/loader-runner@2.4.0/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
[ERROR]     at iterateNormalLoaders (/data/sources/github.com/ops4j/org.ops4j.pax.web/samples/samples-war/war-vaadin20-spring/node_modules/.pnpm/loader-runner@2.4.0/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
[ERROR]     at Array.<anonymous> (/data/sources/github.com/ops4j/org.ops4j.pax.web/samples/samples-war/war-vaadin20-spring/node_modules/.pnpm/loader-runner@2.4.0/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
[ERROR]     at Storage.finished (/data/sources/github.com/ops4j/org.ops4j.pax.web/samples/samples-war/war-vaadin20-spring/node_modules/.pnpm/enhanced-resolve@4.5.0/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
[ERROR]     at /data/sources/github.com/ops4j/org.ops4j.pax.web/samples/samples-war/war-vaadin20-spring/node_modules/.pnpm/enhanced-resolve@4.5.0/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
[ERROR]     at /data/sources/github.com/ops4j/org.ops4j.pax.web/samples/samples-war/war-vaadin20-spring/node_modules/.pnpm/graceful-fs@4.2.8/node_modules/graceful-fs/graceful-fs.js:123:16
[ERROR]     at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)
[ERROR] /data/sources/github.com/ops4j/org.ops4j.pax.web/samples/samples-war/war-vaadin20-spring/node_modules/.pnpm/loader-runner@2.4.0/node_modules/loader-runner/lib/LoaderRunner.js:133
[ERROR] 		if(isError) throw e;
[ERROR] 		            ^
```

I'll use the best fix - disable the sample for now and invite vaadin/node.js experts to help ;)

**Comment by grgrzybek** [comment]
Related to https://github.com/vaadin/flow/issues/12246
