### ISSUE TITLE
Pax Web configuration issue with context processing (security constraints)

### ISSUE THREAD

**Issue by grgrzybek** [ops4j/org.ops4j.pax.web#1720]
https://lists.apache.org/thread/c78h75mpnx47b1441koqp62lhs00o4b6

**Comment by grgrzybek** [comment]
Thanks for the details. I know what I'll be doing tomorrow ;)

**Comment by catshout** [comment]
Bit struggling w/ the formatting but now it seems to be ok :)

**Comment by grgrzybek** [comment]
Confirmed.
The problem is that an attempt to GET `/test1/hello` URI without authentication results in 401. Adding proper authn header gives 404, which is ok. There should be 404 in both cases.

**Comment by catshout** [comment]
Ok, when this have been adjusted as well, could I get a 8.0.4 feature for a final pre-installation an test? I got some other side effects but this might be caused by the manual bundle updates.

**Comment by grgrzybek** [comment]
@catshout ok, I've added even more complicated test (including Whiteboard registration).

If you want to use it quickly in Karaf 4.4.0, please build the latest version (to get it in your `~/.m2/repository`) and then:
```
karaf@root()> feature:repo-remove mvn:org.ops4j.pax.web/pax-web-features/8.0.2/xml/features
Removing features repository: mvn:org.ops4j.pax.web/pax-web-features/8.0.2/xml/features

karaf@root()> feature:repo-add mvn:org.ops4j.pax.web/pax-web-features/8.0.4-SNAPSHOT/xml/features
Adding feature url mvn:org.ops4j.pax.web/pax-web-features/8.0.4-SNAPSHOT/xml/features

karaf@root()> feature:install pax-web-http-jetty
```

**Comment by catshout** [comment]
Doesn't completely work. See the history ..

```
./karaf
karaf: JAVA_HOME not set; results may vary
        __ __                  ____
       / //_/____ __________ _/ __/
      / ,<  / __ `/ ___/ __ `/ /_
     / /| |/ /_/ / /  / /_/ / __/
    /_/ |_|\__,_/_/   \__,_/_/

  Apache Karaf (4.4.0)

Hit '<tab>' for a list of available commands
and '[cmd] --help' for help on a specific command.
Hit '<ctrl-d>' or type 'system:shutdown' or 'logout' to shutdown Karaf.

karaf@root()> feature:repo-add hawtio 2.14.5
Adding feature url mvn:io.hawt/hawtio-karaf/2.14.5/xml/features
karaf@root()> feature:repo-add activemq 5.17.1
Adding feature url mvn:org.apache.activemq/activemq-karaf/5.17.1/xml/features
karaf@root()> feature:repo-add camel 3.14.3
Adding feature url mvn:org.apache.camel.karaf/apache-camel/3.14.3/xml/features
karaf@root()> feature:repo-remove mvn:org.ops4j.pax.web/pax-web-features/8.0.2/xml/features
Removing features repository: mvn:org.ops4j.pax.web/pax-web-features/8.0.2/xml/features
karaf@root()> feature:repo-add mvn:org.ops4j.pax.web/pax-web-features/8.0.4-SNAPSHOT/xml/features
Adding feature url mvn:org.ops4j.pax.web/pax-web-features/8.0.4-SNAPSHOT/xml/features
karaf@root()> feature:install pax-web-jetty
karaf@root()> feature:install hawtio activemq-broker-noweb camel camel-jms jms camel-http camel-servlet camel-swagger-java camel-ftp camel-jackson camel-jsonpath camel-json-validator camel-zipfile camel-velocity camel-groovy camel-salesforce camel-kafka
org.apache.felix.resolver.reason.ReasonException: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=pax-web-jetty; type=karaf.feature; version="[9.4.46.v20220331,9.4.46.v20220331]"; filter:="(&(osgi.identity=pax-web-jetty)(type=karaf.feature)(version>=9.4.46.v20220331)(version<=9.4.46.v20220331))" [caused by: Unable to resolve pax-web-jetty/9.4.46.v20220331: missing requirement [pax-web-jetty/9.4.46.v20220331] osgi.identity; osgi.identity=org.ops4j.pax.web.pax-web-compatibility-servlet31; type=osgi.fragment; version="[8.0.2,8.0.2]"; resolution:=mandatory [caused by: Fragment was not selected for attachment: org.ops4j.pax.web.pax-web-compatibility-servlet31/8.0.2]]
        at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1341)
        at org.apache.felix.resolver.ResolverImpl.doResolve(ResolverImpl.java:433)
        at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:420)
        at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:374)
        at org.apache.karaf.features.internal.region.SubsystemResolver.resolve(SubsystemResolver.java:256)
        at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:399)
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1069)
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.lambda$doProvisionInThread$13(FeaturesServiceImpl.java:1004)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.apache.felix.resolver.reason.ReasonException: Unable to resolve pax-web-jetty/9.4.46.v20220331: missing requirement [pax-web-jetty/9.4.46.v20220331] osgi.identity; osgi.identity=org.ops4j.pax.web.pax-web-compatibility-servlet31; type=osgi.fragment; version="[8.0.2,8.0.2]"; resolution:=mandatory [caused by: Fragment was not selected for attachment: org.ops4j.pax.web.pax-web-compatibility-servlet31/8.0.2]
        at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1341)
        ... 12 more
Caused by: org.apache.felix.resolver.reason.ReasonException: Fragment was not selected for attachment: org.ops4j.pax.web.pax-web-compatibility-servlet31/8.0.2
        at org.apache.felix.resolver.Candidates$FragmentNotSelectedError.toException(Candidates.java:1305)
        ... 13 more
Error executing command: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=pax-web-jetty; type=karaf.feature; version="[9.4.46.v20220331,9.4.46.v20220331]"; filter:="(&(osgi.identity=pax-web-jetty)(type=karaf.feature)(version>=9.4.46.v20220331)(version<=9.4.46.v20220331))" [caused by: Unable to resolve pax-web-jetty/9.4.46.v20220331: missing requirement [pax-web-jetty/9.4.46.v20220331] osgi.identity; osgi.identity=org.ops4j.pax.web.pax-web-compatibility-servlet31; type=osgi.fragment; version="[8.0.2,8.0.2]"; resolution:=mandatory [caused by: Fragment was not selected for attachment: org.ops4j.pax.web.pax-web-compatibility-servlet31/8.0.2]]
karaf@root()>
```

The local repo has been defined as

```
#
# Path to the local Maven repository which is used to avoid downloading
# artifacts when they already exist locally.
# The value of this property will be extracted from the settings.xml file
# above, or defaulted to:
#     System.getProperty( "user.home" ) + "/.m2/repository"
# leaving this option commented makes the system dependent on external
# configuration, which is not always desired
# "localRepository" is the target location for artifacts downloaded from
# "remote repositories"
org.ops4j.pax.url.mvn.localRepository=/opt/apache-karaf/system
```

I did run the maven build and copied afterwards the maven repo

```
cp -r /home/casisp/.m2/repository/org/ops4j /opt/apache-karaf/system/org
```

jetty install worked, but than I got the error above.

**Comment by grgrzybek** [comment]
Hmm, this:

osgi.identity=org.ops4j.pax.web.pax-web-compatibility-servlet31;
> type=osgi.fragment; version="[8.0.2,8.0.2]
>

means you still have 8.0.2 somewhere...

In my case, I've started with fresh Karaf 4.4.0 and just replaced 8.0.2
with 8.0.4-SNAPSHOT in
$KARAF_HOME/system/org/apache/karaf/features/standard/4.4.0/standard-4.4.0-features.xml


then I didn't have to replace anything.

regards
Grzegorz Grzybek

śr., 25 maj 2022 o 14:44 catshout ***@***.***> napisał(a):
