### ISSUE TITLE
Starting with both http & https disabled throws exception on startup

### ISSUE THREAD

**Issue by marcanpilami** [ops4j/org.ops4j.pax.web#1726]
Hi!

My use case is a bit weird: I want the Jetty server not to start when the bundle loads, and wait for user input to start on a given port.
So I have set both  `org.osgi.service.http.enabled` and `org.osgi.service.http.secure.enabled` to false. As a result, I get 

```
java.lang.NullPointerException: Cannot read the array length because "array" is null
	at java.base/java.util.Arrays.stream(Arrays.java:5428)
	at org.ops4j.pax.web.service.internal.Activator$AddressConfiguration.stateChanged(Activator.java:908)
	at org.ops4j.pax.web.service.jetty.internal.JettyServerController.addListener(JettyServerController.java:144)
	at org.ops4j.pax.web.service.internal.Activator.performConfiguration(Activator.java:606)
	at org.ops4j.pax.web.service.internal.Activator.updateController(Activator.java:441)
	at org.ops4j.pax.web.service.internal.Activator.lambda$updateServerControllerFactory$1(Activator.java:347)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Unable to start Pax Web server: Cannot read the array length because "array" is null
```

This is due to the fact that Jetty starts without listeners, and then returns a null list of bound addresses instead of an empty list. I believe this is a bug - but either we need an explicit configuration warning "this is stupid", or allow it. In all cases, I'm still looking for a way not to start Jetty on startup, which would make this point moot - I'd be happy to submit a PR that would prevent starting up on the presence of a specific configuration key.

With version 8.0.4, Jetty 9.4.46.v20220331.

Thanks,
Marc-Antoine

**Comment by grgrzybek** [comment]
Thanks for the report! I didn't anticipate someone may want that ;)
PR would be appreciated - please remember about Tomcat and Undertow as well.
I can look at it next week.
