### ISSUE TITLE
NoClassDefFoundError: javax/servlet/jsp/tagext/TagVariableInfo when Karaf is restarted

### ISSUE THREAD

**Issue by rhierlmeier** [ops4j/org.ops4j.pax.web#1746]
I have in Karaf 4.4.1 Hawtio installed. When I restart this Karaf instance I often (not always) get this error:

```
2022.08.05 17:49:19,711	[paxweb-config-3-thread-1 (deploy /hawtio)]	[INFO]	[JettyServerWrapper]	Changing error page configuration for context /hawtio	[]	[]
2022.08.05 17:49:19,711	[paxweb-config-3-thread-1 (deploy /hawtio)]	[INFO]	[JettyServerWrapper]	Starting Jetty context "/hawtio" with default Osgi Context OsgiContextModel{WAB,id=OCM-31,name='/hawtio',path='/hawtio',bundle=io.hawt.hawtio-osgi,context=WebContainerContextWrapper{bundle=io.hawt.hawtio-osgi [262],contextId='/hawtio',delegate=org.ops4j.pax.web.extender.war.internal.WebApplicationHelper@9cda7c3}}	[]	[]
2022.08.05 17:49:19,711	[wab-extender-1-thread-2]	[ERROR]	[BundleWebApplication]	Problem processing Web Application "/hawtio" for bundle io.hawt.hawtio-osgi/2.15.0: javax/servlet/jsp/tagext/TagVariableInfo	[]	[ java.lang.RuntimeException: javax/servlet/jsp/tagext/TagVariableInfo
	at org.ops4j.pax.web.service.spi.model.ServerModel.runSilently(ServerModel.java:656)
	at org.ops4j.pax.web.service.internal.HttpServiceEnabled$WebAppWebContainer.sendBatch(HttpServiceEnabled.java:2466)
	at org.ops4j.pax.web.extender.war.internal.model.BundleWebApplication.deploy(BundleWebApplication.java:745)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: javax/servlet/jsp/tagext/TagVariableInfo
	at org.ops4j.pax.web.service.spi.model.ServerModel.run(ServerModel.java:562)
	at org.ops4j.pax.web.service.spi.model.ServerModel.runSilently(ServerModel.java:651)
	... 9 more
	Suppressed: java.lang.Throwable
		at org.ops4j.pax.web.service.spi.model.ServerModel.run(ServerModel.java:534)
		... 10 more
Caused by: java.lang.NoClassDefFoundError: javax/servlet/jsp/tagext/TagVariableInfo
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2729)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3076)
	at java.lang.Class.getMethod0(Class.java:3046)
	at java.lang.Class.getMethod(Class.java:1812)
	at org.apache.tomcat.util.descriptor.tld.TldRuleSet$GenericBooleanRule.<init>(TldRuleSet.java:387)
	at org.apache.tomcat.util.descriptor.tld.TldRuleSet$GenericBooleanRule.<init>(TldRuleSet.java:382)
	at org.apache.tomcat.util.descriptor.tld.TldRuleSet.addRuleInstances(TldRuleSet.java:96)
	at org.apache.tomcat.util.digester.Digester.addRuleSet(Digester.java:1612)
	at org.apache.tomcat.util.descriptor.DigesterFactory.newDigester(DigesterFactory.java:171)
	at org.apache.tomcat.util.descriptor.tld.TldParser.<init>(TldParser.java:49)
	at org.apache.tomcat.util.descriptor.tld.TldParser.<init>(TldParser.java:44)
	at org.apache.jasper.servlet.TldScanner.<init>(TldScanner.java:84)
	at org.ops4j.pax.web.jsp.PaxWebTldScanner.<init>(PaxWebTldScanner.java:53)
	at org.ops4j.pax.web.jsp.JasperInitializer.newTldScanner(JasperInitializer.java:205)
	at org.apache.jasper.servlet.JasperInitializer.onStartup(JasperInitializer.java:81)
	at org.ops4j.pax.web.jsp.JasperInitializer.onStartup(JasperInitializer.java:141)
	at org.ops4j.pax.web.service.spi.servlet.SCIWrapper.onStartup(SCIWrapper.java:43)
	at org.ops4j.pax.web.service.jetty.internal.PaxWebServletContextHandler.lambda$startContext$1(PaxWebServletContextHandler.java:257)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.ops4j.pax.web.service.jetty.internal.PaxWebServletContextHandler.startContext(PaxWebServletContextHandler.java:251)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:916)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:288)
	at org.ops4j.pax.web.service.jetty.internal.PaxWebServletContextHandler.doStart(PaxWebServletContextHandler.java:307)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at org.ops4j.pax.web.service.jetty.internal.JettyServerWrapper.ensureServletContextStarted(JettyServerWrapper.java:2378)
	at org.ops4j.pax.web.service.jetty.internal.JettyServerWrapper.visitTransactionStateChange(JettyServerWrapper.java:731)
	at org.ops4j.pax.web.service.spi.task.TransactionStateChange.accept(TransactionStateChange.java:35)
	at org.ops4j.pax.web.service.spi.task.Batch.accept(Batch.java:430)
	at org.ops4j.pax.web.service.jetty.internal.JettyServerController.sendBatch(JettyServerController.java:168)
	at org.ops4j.pax.web.service.internal.HttpServiceEnabled$WebAppWebContainer.lambda$sendBatch$0(HttpServiceEnabled.java:2495)
	at org.ops4j.pax.web.service.spi.model.ServerModel.lambda$run$2(ServerModel.java:540)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
	... 7 more
Caused by: java.lang.ClassNotFoundException: javax.servlet.jsp.tagext.TagVariableInfo not found by org.ops4j.pax.web.pax-web-tomcat-common [231]
	at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1591)
	at org.apache.felix.framework.BundleWiringImpl.access$300(BundleWiringImpl.java:79)
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1976)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 40 more
]
```

**Comment by grgrzybek** [comment]
@rhierlmeier do you simply restart Karaf using `bin/stop` + `bin/start`? Or programmatically?

**Comment by grgrzybek** [comment]
I tried restarting many times but without luck... Can you send me full log please?

**Comment by rhierlmeier** [comment]
Here are the logs: [karaf.log](https://210922rtyenaavi3ide.nextcloud.hosting.zone/s/DLRy95rkxkRiNWw)

**Comment by grgrzybek** [comment]
Thanks @rhierlmeier .

I see that pax-web-tomcat-common has quite high bundle ID and you're running on Windows.
May I see the IDs of all the bundles? (output of `la -l`)

**Comment by rhierlmeier** [comment]
Yes it is on Windows. Here is the bundle list: [bundles.txt](https://210922rtyenaavi3ide.nextcloud.hosting.zone/s/6CtYAi84bbpjit7)

**Comment by grgrzybek** [comment]
Reproduced after changing bundle id of pax-web-tomcat-common to just 1 more than hawtio:
```
2022-08-26T12:20:50,335 | ERROR | wab-extender-1-thread-1 (/hawtio [86]) | BundleWebApplication             | 77 - org.ops4j.pax.web.pax-web-extender-war - 8.0.6 | Problem processing Web Application "/hawtio" for bundle io.hawt.hawtio-osgi/2.15.0: javax/servlet/jsp/tagext/TagVariableInfo
java.lang.RuntimeException: javax/servlet/jsp/tagext/TagVariableInfo
	at org.ops4j.pax.web.service.spi.model.ServerModel.runSilently(ServerModel.java:656) ~[?:?]
	at org.ops4j.pax.web.service.internal.HttpServiceEnabled$WebAppWebContainer.sendBatch(HttpServiceEnabled.java:2466) ~[?:?]
	at org.ops4j.pax.web.extender.war.internal.model.BundleWebApplication.deploy(BundleWebApplication.java:745) ~[?:?]
	at org.ops4j.pax.web.extender.war.internal.model.BundleWebApplication.scheduleIfPossible(BundleWebApplication.java:378) ~[?:?]
	at org.ops4j.pax.web.extender.war.internal.model.BundleWebApplication.start(BundleWebApplication.java:254) ~[?:?]
	at org.ops4j.pax.web.extender.war.internal.WarExtenderContext$WabExtension.start(WarExtenderContext.java:757) ~[?:?]
	at org.apache.felix.utils.extender.AbstractExtender$1.run(AbstractExtender.java:260) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_301]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_301]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_301]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[?:1.8.0_301]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_301]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_301]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_301]
Caused by: java.lang.RuntimeException: javax/servlet/jsp/tagext/TagVariableInfo
	at org.ops4j.pax.web.service.spi.model.ServerModel.run(ServerModel.java:562) ~[?:?]
	at org.ops4j.pax.web.service.spi.model.ServerModel.runSilently(ServerModel.java:651) ~[?:?]
	... 13 more
	Suppressed: java.lang.Throwable
		at org.ops4j.pax.web.service.spi.model.ServerModel.run(ServerModel.java:534) ~[?:?]
		at org.ops4j.pax.web.service.spi.model.ServerModel.runSilently(ServerModel.java:651) ~[?:?]
		at org.ops4j.pax.web.service.internal.HttpServiceEnabled$WebAppWebContainer.sendBatch(HttpServiceEnabled.java:2466) ~[?:?]
		at org.ops4j.pax.web.extender.war.internal.model.BundleWebApplication.deploy(BundleWebApplication.java:745) ~[?:?]
		at org.ops4j.pax.web.extender.war.internal.model.BundleWebApplication.scheduleIfPossible(BundleWebApplication.java:378) ~[?:?]
		at org.ops4j.pax.web.extender.war.internal.model.BundleWebApplication.start(BundleWebApplication.java:254) ~[?:?]
		at org.ops4j.pax.web.extender.war.internal.WarExtenderContext$WabExtension.start(WarExtenderContext.java:757) ~[?:?]
		at org.apache.felix.utils.extender.AbstractExtender$1.run(AbstractExtender.java:260) ~[?:?]
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_301]
		at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_301]
		at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_301]
		at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[?:1.8.0_301]
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_301]
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_301]
		at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_301]
Caused by: java.lang.NoClassDefFoundError: javax/servlet/jsp/tagext/TagVariableInfo
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_301]
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[?:1.8.0_301]
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048) ~[?:1.8.0_301]
	at java.lang.Class.getMethod0(Class.java:3018) ~[?:1.8.0_301]
	at java.lang.Class.getMethod(Class.java:1784) ~[?:1.8.0_301]
	at org.apache.tomcat.util.descriptor.tld.TldRuleSet$GenericBooleanRule.<init>(TldRuleSet.java:387) ~[?:?]
	at org.apache.tomcat.util.descriptor.tld.TldRuleSet$GenericBooleanRule.<init>(TldRuleSet.java:382) ~[?:?]
	at org.apache.tomcat.util.descriptor.tld.TldRuleSet.addRuleInstances(TldRuleSet.java:96) ~[?:?]
	at org.apache.tomcat.util.digester.Digester.addRuleSet(Digester.java:1612) ~[?:?]
	at org.apache.tomcat.util.descriptor.DigesterFactory.newDigester(DigesterFactory.java:171) ~[?:?]
	at org.apache.tomcat.util.descriptor.tld.TldParser.<init>(TldParser.java:49) ~[?:?]
	at org.apache.tomcat.util.descriptor.tld.TldParser.<init>(TldParser.java:44) ~[?:?]
	at org.apache.jasper.servlet.TldScanner.<init>(TldScanner.java:84) ~[?:?]
	at org.ops4j.pax.web.jsp.PaxWebTldScanner.<init>(PaxWebTldScanner.java:53) ~[?:?]
	at org.ops4j.pax.web.jsp.JasperInitializer.newTldScanner(JasperInitializer.java:205) ~[?:?]
	at org.apache.jasper.servlet.JasperInitializer.onStartup(JasperInitializer.java:81) ~[?:?]
	at org.ops4j.pax.web.jsp.JasperInitializer.onStartup(JasperInitializer.java:141) ~[?:?]
	at org.ops4j.pax.web.service.spi.servlet.SCIWrapper.onStartup(SCIWrapper.java:43) ~[?:?]
	at org.ops4j.pax.web.service.jetty.internal.PaxWebServletContextHandler.lambda$startContext$1(PaxWebServletContextHandler.java:257) ~[?:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_301]
	at org.ops4j.pax.web.service.jetty.internal.PaxWebServletContextHandler.startContext(PaxWebServletContextHandler.java:251) ~[?:?]
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:916) ~[?:?]
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:288) ~[?:?]
	at org.ops4j.pax.web.service.jetty.internal.PaxWebServletContextHandler.doStart(PaxWebServletContextHandler.java:307) ~[?:?]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73) ~[?:?]
	at org.ops4j.pax.web.service.jetty.internal.JettyServerWrapper.ensureServletContextStarted(JettyServerWrapper.java:2378) ~[?:?]
	at org.ops4j.pax.web.service.jetty.internal.JettyServerWrapper.visitTransactionStateChange(JettyServerWrapper.java:731) ~[?:?]
	at org.ops4j.pax.web.service.spi.task.TransactionStateChange.accept(TransactionStateChange.java:35) ~[?:?]
	at org.ops4j.pax.web.service.spi.task.Batch.accept(Batch.java:430) ~[?:?]
	at org.ops4j.pax.web.service.jetty.internal.JettyServerController.sendBatch(JettyServerController.java:168) ~[?:?]
	at org.ops4j.pax.web.service.internal.HttpServiceEnabled$WebAppWebContainer.lambda$sendBatch$0(HttpServiceEnabled.java:2495) ~[?:?]
	at org.ops4j.pax.web.service.spi.model.ServerModel.lambda$run$2(ServerModel.java:540) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604) ~[?:1.8.0_301]
	... 7 more
Caused by: java.lang.ClassNotFoundException: javax.servlet.jsp.tagext.TagVariableInfo not found by org.ops4j.pax.web.pax-web-tomcat-common [87]
	at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1591) ~[?:?]
	at org.apache.felix.framework.BundleWiringImpl.access$300(BundleWiringImpl.java:79) ~[?:?]
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1976) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_301]
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_301]
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[?:1.8.0_301]
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048) ~[?:1.8.0_301]
	at java.lang.Class.getMethod0(Class.java:3018) ~[?:1.8.0_301]
	at java.lang.Class.getMethod(Class.java:1784) ~[?:1.8.0_301]
	at org.apache.tomcat.util.descriptor.tld.TldRuleSet$GenericBooleanRule.<init>(TldRuleSet.java:387) ~[?:?]
	at org.apache.tomcat.util.descriptor.tld.TldRuleSet$GenericBooleanRule.<init>(TldRuleSet.java:382) ~[?:?]
	at org.apache.tomcat.util.descriptor.tld.TldRuleSet.addRuleInstances(TldRuleSet.java:96) ~[?:?]
	at org.apache.tomcat.util.digester.Digester.addRuleSet(Digester.java:1612) ~[?:?]
	at org.apache.tomcat.util.descriptor.DigesterFactory.newDigester(DigesterFactory.java:171) ~[?:?]
	at org.apache.tomcat.util.descriptor.tld.TldParser.<init>(TldParser.java:49) ~[?:?]
	at org.apache.tomcat.util.descriptor.tld.TldParser.<init>(TldParser.java:44) ~[?:?]
	at org.apache.jasper.servlet.TldScanner.<init>(TldScanner.java:84) ~[?:?]
	at org.ops4j.pax.web.jsp.PaxWebTldScanner.<init>(PaxWebTldScanner.java:53) ~[?:?]
	at org.ops4j.pax.web.jsp.JasperInitializer.newTldScanner(JasperInitializer.java:205) ~[?:?]
	at org.apache.jasper.servlet.JasperInitializer.onStartup(JasperInitializer.java:81) ~[?:?]
	at org.ops4j.pax.web.jsp.JasperInitializer.onStartup(JasperInitializer.java:141) ~[?:?]
	at org.ops4j.pax.web.service.spi.servlet.SCIWrapper.onStartup(SCIWrapper.java:43) ~[?:?]
	at org.ops4j.pax.web.service.jetty.internal.PaxWebServletContextHandler.lambda$startContext$1(PaxWebServletContextHandler.java:257) ~[?:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_301]
	at org.ops4j.pax.web.service.jetty.internal.PaxWebServletContextHandler.startContext(PaxWebServletContextHandler.java:251) ~[?:?]
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:916) ~[?:?]
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:288) ~[?:?]
	at org.ops4j.pax.web.service.jetty.internal.PaxWebServletContextHandler.doStart(PaxWebServletContextHandler.java:307) ~[?:?]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73) ~[?:?]
	at org.ops4j.pax.web.service.jetty.internal.JettyServerWrapper.ensureServletContextStarted(JettyServerWrapper.java:2378) ~[?:?]
	at org.ops4j.pax.web.service.jetty.internal.JettyServerWrapper.visitTransactionStateChange(JettyServerWrapper.java:731) ~[?:?]
	at org.ops4j.pax.web.service.spi.task.TransactionStateChange.accept(TransactionStateChange.java:35) ~[?:?]
	at org.ops4j.pax.web.service.spi.task.Batch.accept(Batch.java:430) ~[?:?]
	at org.ops4j.pax.web.service.jetty.internal.JettyServerController.sendBatch(JettyServerController.java:168) ~[?:?]
	at org.ops4j.pax.web.service.internal.HttpServiceEnabled$WebAppWebContainer.lambda$sendBatch$0(HttpServiceEnabled.java:2495) ~[?:?]
	at org.ops4j.pax.web.service.spi.model.ServerModel.lambda$run$2(ServerModel.java:540) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604) ~[?:1.8.0_301]
	... 7 more
```

**Comment by grgrzybek** [comment]
Easily reproducible now also on Linux.

**Comment by grgrzybek** [comment]
@rhierlmeier the point is that `pax-web-tomcat-common` has optional imports to packages provided by `pax-web-jsp`. If its wiring includes wires to `pax-web-jsp`, everything works, but when there are no such wires, it fails with the exception we're seeing.

Refreshing `pax-web-tomcat-common` bundle helps, but we need better solution here.
