### ISSUE TITLE
Pax Web 8.0.6 & Swagger UI problem

### ISSUE THREAD

**Issue by grgrzybek** [ops4j/org.ops4j.pax.web#1747]
During our upgrading to the latest karaf 4.4.1 I found a problem with CXF 3.5.3 and Swagger UI (3.52.5). We dynamically export openapi descriptions so when developers
display a webpage localhost:8181/cxf they are able to display Swagger UI for a specific endpoint.
Everything worked fine with Karaf 4.3.6 but now I can see this exception:
```
10:58:19.288 ERROR [qtp568267022-1055] HTTP 404 Not Found
javax.ws.rs.NotFoundException: HTTP 404 Not Found
    at org.apache.cxf.jaxrs.swagger.ui.SwaggerUiService.getResource(SwaggerUiService.java:155) ~[!/:3.5.3]
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
    at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
    at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179) ~[!/:3.5.3]
    at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96) ~[!/:3.5.3]
    at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201) ~[!/:3.5.3]
    at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104) ~[!/:3.5.3]
    at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59) ~[!/:3.5.3]
    at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96) ~[!/:3.5.3]
    at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307) ~[!/:3.5.3]
    at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121) ~[!/:3.5.3]
    at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:265) ~[!/:3.5.3]
    at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234) ~[!/:3.5.3]
    at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208) ~[!/:3.5.3]
    at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160) ~[!/:3.5.3]
    at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:225) ~[!/:3.5.3]
    at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:304) ~[!/:3.5.3]
    at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doGet(AbstractHTTPServlet.java:222) ~[!/:3.5.3]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:497) ~[!/:4.0.4]
    at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:279) ~[!/:3.5.3]
    at org.ops4j.pax.web.service.spi.servlet.OsgiInitializedServlet.service(OsgiInitializedServlet.java:74) ~[?:?]
    at org.eclipse.jetty.servlet.ServletHolder$NotAsync.service(ServletHolder.java:1450) ~[?:?]
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799) ~[?:?]
    at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1656) ~[?:?]
    at org.ops4j.pax.web.service.spi.servlet.OsgiFilterChain.doFilter(OsgiFilterChain.java:100) ~[?:?]
    at org.ops4j.pax.web.service.jetty.internal.PaxWebServletHandler.doHandle(PaxWebServletHandler.java:310) ~[?:?]
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) ~[?:?]
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:600) ~[?:?]
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[?:?]
    at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235) ~[?:?]
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624) ~[?:?]
    at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) ~[?:?]
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1440) ~[?:?]
    at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) ~[?:?]
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:505) ~[?:?]
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594) ~[?:?]
    at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) ~[?:?]
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1355) ~[?:?]
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[?:?]
    at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:191) ~[?:?]
    at org.ops4j.pax.web.service.jetty.internal.PrioritizedHandlerCollection.handle(PrioritizedHandlerCollection.java:96) ~[?:?]
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[?:?]
    at org.eclipse.jetty.server.Server.handle(Server.java:516) ~[?:?]
    at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487) ~[?:?]
    at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732) ~[?:?]
    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479) ~[?:?]
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277) ~[?:?]
    at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) ~[?:?]
    at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) ~[?:?]
    at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) ~[?:?]
    at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338) ~[?:?]
    at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315) ~[?:?]
    at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173) ~[?:?]
    at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131) ~[?:?]
    at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409) ~[?:?]
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883) ~[?:?]
    at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034) ~[?:?]
    at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.io.IOException: Resource does not exist: bundle://91689fbf-561e-4103-8a87-941e22597525_256.0:0/META-INF/resources/webjars/swagger-ui/3.52.5//index.html
    at org.apache.felix.framework.URLHandlersBundleURLConnection.<init>(URLHandlersBundleURLConnection.java:137) ~[?:?]
    at org.apache.felix.framework.URLHandlersBundleStreamHandler.openConnection(URLHandlersBundleStreamHandler.java:66) ~[?:?]
    at java.net.URL.openConnection(URL.java:1094) ~[?:?]
    at java.net.URL.openStream(URL.java:1161) ~[?:?]
    at org.apache.cxf.jaxrs.swagger.ui.SwaggerUiService.getResource(SwaggerUiService.java:149) ~[!/:3.5.3]
    ... 59 more
```

I also checked Swagger UI bundle and I could see that a file META-INF/resources/webjars/swagger-ui/3.52.5/index.html existed.

Within our feature we install these dependencies:
```xml
<bundle>mvn:org.webjars/swagger-ui/3.52.5</bundle>
<feature>cxf-rs-description-openapi-v3</feature>
```

Could it be a bug?

Jakub

**Comment by grgrzybek** [comment]
Hello @jherkel

I've installed:
* CXF 3.5.3
* mvn:org.webjars/swagger-ui/3.52.5

But I guess without any OpenAPI configured CXF endpoints, I can't reproduce your problem... Do you have a sample rest endpoint bundle I could check?

**Comment by ida-greuelr** [comment]
Same problem here:
```
karaf  | javax.ws.rs.NotFoundException: HTTP 404 Not Found
karaf  | 	at org.apache.cxf.jaxrs.swagger.ui.SwaggerUiService.getResource(SwaggerUiService.java:155) ~[!/:3.4.8]
karaf  | 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
karaf  | 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
karaf  | 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
[...]
karaf  | Caused by: java.io.IOException: Resource does not exist: bundle://de5de756-4284-47ce-946d-87282254e795_372.0:0/META-INF/resources/webjars/swagger-ui/4.14.0//index.html
karaf  | 	at org.apache.felix.framework.URLHandlersBundleURLConnection.<init>(URLHandlersBundleURLConnection.java:137) ~[?:?]
karaf  | 	at org.apache.felix.framework.URLHandlersBundleStreamHandler.openConnection(URLHandlersBundleStreamHandler.java:66) ~[?:?]
karaf  | 	at java.net.URL.openConnection(URL.java:1094) ~[?:?]
karaf  | 	at java.net.URL.openStream(URL.java:1161) ~[?:?]
karaf  | 	at org.apache.cxf.jaxrs.swagger.ui.SwaggerUiService.getResource(SwaggerUiService.java:149) ~[!/:3.4.8]
karaf  | 	... 59 more
```
- Karaf 4.4.1
- Pax Web 8.0.6
- CXF 3.4.8 (**Swagger2** not openAPIv3 with cxf-rt-rs-service-description-swagger-ui)
- swagger-ui 4.14.0

We startet migration from karaf 4.3.7 -> 4.4.1 and upgraded  cxf 3.4.3  -> 3.4.8. There are fixes in the release notes from CXF for the recent versions 3.4.8 and 3.5.2
- 3.4.8: https://issues.apache.org/jira/secure/ReleaseNote.jspa?projectId=12310511&version=12351568
- 3.5.2: https://issues.apache.org/jira/secure/ReleaseNote.jspa?projectId=12310511&version=12351552

pointing to this issue:
- https://issues.apache.org/jira/browse/CXF-8683
- 
which seems to fix issues with the SwaggerUIService.
**But version 3.4.8 still results in the above mentioned exception.**

Deployed Pax versions `list -t 0 | grep -i pax`:
```
  2 │ Active   │   5 │ 2.6.11                              │ OPS4J Pax Url - mvn:
  6 │ Active   │   8 │ 2.1.3                               │ OPS4J Pax Logging - API
  7 │ Active   │   8 │ 2.1.3                               │ OPS4J Pax Logging - Log4Jv2 implementation
 19 │ Active   │  10 │ 2.6.11                              │ OPS4J Pax Url - wrap:
347 │ Active   │  80 │ 1.5.3                               │ OPS4J Pax JDBC Generic Driver Extender
348 │ Active   │  80 │ 1.5.3                               │ OPS4J Pax JDBC Config
349 │ Active   │  80 │ 1.5.3                               │ OPS4J Pax JDBC MariaDB Driver Adapter
350 │ Active   │  80 │ 1.5.3                               │ OPS4J Pax JDBC Oracle Driver Adapter
351 │ Active   │  80 │ 1.5.3                               │ OPS4J Pax JDBC Pooling Support Base
352 │ Active   │  80 │ 1.5.3                               │ OPS4J Pax JDBC Pooling DBCP2
353 │ Active   │  80 │ 1.5.3                               │ OPS4J Pax JDBC Pooling HikariCP
354 │ Active   │  80 │ 1.8.5                               │ OPS4J Pax Swissbox :: Property
355 │ Active   │  30 │ 8.0.6                               │ OPS4J Pax Web - API
356 │ Resolved │  30 │ 8.0.6                               │ OPS4J Pax Web - Annotation 1.3 compatibility, Hosts: 161
357 │ Resolved │  30 │ 8.0.6                               │ OPS4J Pax Web - EL 2.2 compatibility, Hosts: 168
358 │ Resolved │  30 │ 8.0.6                               │ OPS4J Pax Web - Servlet API 3.1 compatibility, Hosts: 163
359 │ Active   │  30 │ 8.0.6                               │ OPS4J Pax Web - Jetty
360 │ Active   │  30 │ 8.0.6                               │ OPS4J Pax Web - Runtime
361 │ Active   │  30 │ 8.0.6                               │ OPS4J Pax Web - Service SPI (internal)
362 │ Active   │  30 │ 8.0.6                               │ OPS4J Pax Web - Tomcat Common
363 │ Active   │  30 │ 8.0.6                               │ OPS4J Pax Web - WebSocket support
```
Deployed swagger related bundles `list -t 0 | grep -i swagger`:
```
156 │ Active   │  35 │ 1.6.6                               │ swagger-annotations
157 │ Active   │  35 │ 1.6.6                               │ swagger-core
158 │ Active   │  35 │ 1.6.6                               │ swagger-jaxrs
159 │ Active   │  35 │ 1.6.6                               │ swagger-models
227 │ Active   │  40 │ 3.4.8                               │ Apache CXF JAX-RS Service Description OpenAPI/Swagger Co
228 │ Active   │  40 │ 3.4.8                               │ Apache CXF JAX-RS Service Description Swagger
229 │ Active   │  35 │ 3.4.8                               │ Apache CXF JAX-RS Service Description Swagger UI integra
372 │ Active   │  80 │ 4.14.0                              │ Swagger UI
```

**Comment by grgrzybek** [comment]
@ida-greuelr could you share sample CXF application which exposes swagger-enabled endpoint?

**Comment by ida-greuelr** [comment]
> @ida-greuelr could you share sample CXF application which exposes swagger-enabled endpoint?

Let me see if I can hack a simple but complete example together, without violating our company's compliance. This will take a moment...

**Comment by grgrzybek** [comment]
Thanks upfront! I simply don't have enough time now to prepare such example.

**Comment by ida-greuelr** [comment]
Feel free to try it out. I have added a small README with step by step procedure.
The example is based on a cleaned existing project. I have removed all sensitive code, but the whole build setup and karaf configuration is almost the same.

The only gap is the log configuration of the karaf. It is not logging the inner java.io.Exception correctly.
You can find the logging config at `com.mycompany.swaggertest.distribution/swaggertest-product/src/main/resources/etc`.

Another important point is `com.mycompany.swaggertest.suite/monitoring/src/main/resources/OSGI-INF/blueprint/blueprint.xml`. Here is the initialization of the cxf swagger feature, which auto-generates the swagger-urls for CXF endpoints.

You can find the swagger2 annotations at:
`com.mycompany.swaggertest.suite/monitoring/src/main/java/com/mycompany/swaggertest/suite/monitoring/prometheus/PrometheusMetricsService.java:54`

[swaggertest.zip](https://github.com/ops4j/org.ops4j.pax.web/files/9462492/swaggertest.zip)

**Comment by grgrzybek** [comment]
Thanks! - I should have a look this week.

**Comment by grgrzybek** [comment]
Initially I thought it's the problem with Pax Web 8 and how it handles `/META-INF/resources/webjars/swagger-ui/3.52.5//index.html` URI using Pax Web mechanisms.

However, the resource can't be found within constructor of `org.apache.felix.framework.URLHandlersBundleURLConnection#URLHandlersBundleURLConnection` class, where the passed URL is:
```
bundle://5167bfb2-99bd-44c1-abbe-c2b3b0e88dc2_162.0:0/META-INF/resources/webjars/swagger-ui/3.52.5//index.html
```

Felix simply calls `java.lang.ClassLoader#getResource()` on an instance of `org.apache.felix.framework.BundleWiringImpl$BundleClassLoader` fir `org.webjars.swagger-ui ` bundle.

Eventually, `m_zipFile.getEntry("META-INF/resources/webjars/swagger-ui/3.52.5//index.html")` returns null on `org.apache.felix.framework.cache.JarContent` for `org.webjars.swagger-ui ` bundle.

It would return an entry if not the double slash...
Checking.

**Comment by grgrzybek** [comment]
The duplicate slash is added inside `org.apache.cxf.jaxrs.swagger.ui.OsgiSwaggerUiResolver#getSwaggerUiRoot()` and ... it's reported with [CXF-8750](https://issues.apache.org/jira/browse/CXF-8750) and fixed with 3.4.9, 3.5.4, 3.6.0 and 4.0.0 versions.

I believe it was working with Karaf 4.3, because it's using Felix 6 (OSGi R7), while Karaf 4.4 moved to Felix 7 (OSGi R8) which handles `bundle:` URIs in different way.

**Comment by grgrzybek** [comment]
With [CXF-8750](https://issues.apache.org/jira/browse/CXF-8750) fixed, I can navigate to http://localhost:8181/cxf/ and see:
```
Endpoint address: http://localhost:8181/cxf/rest
WADL : http://localhost:8181/cxf/rest?_wadl
Swagger : http://localhost:8181/cxf/rest/api-docs?url=/cxf/rest/swagger.json
```

Then at http://localhost:8181/cxf/rest/api-docs?url=/cxf/rest/swagger.json I can see nice Swagger UI, from which I can invoke my sample hello endpoint with Swagger annotations at http://localhost:8181/cxf/rest/api-docs?url=/cxf/rest/swagger.json#/default/hello.

**Comment by grgrzybek** [comment]
Thank you very much @ida-greuelr for your example - it was very helpful. I've added very trivial Pax Web example here: https://github.com/ops4j/org.ops4j.pax.web/tree/main/samples/samples-whiteboard/whiteboard-blueprint-jaxrs

**Comment by grgrzybek** [comment]
Closing as _explained_.
