### ISSUE TITLE
Some WAB deployments stuck 

### ISSUE THREAD

**Issue by swaninga** [ops4j/org.ops4j.pax.web#1750]
Hi,

i'm currently try to update our karaf platform from pax-web version 7.3.x to 8.0.6.
Some WAB are deployed successfully but some not.
I created some thread dumps from time to time to see why the deployment of them do not end.
The threads look all similar to this one:
```
"wab-extender-2-thread-4" Id=324 in RUNNABLE
    at java.base@17.0.4/java.util.Collection.removeIf(Collection.java:576)
    at org.ops4j.pax.web.utils.ClassPathUtil.getBundlesInClassSpace(ClassPathUtil.java:309)
    at org.ops4j.pax.web.utils.ClassPathUtil.getBundlesInClassSpace(ClassPathUtil.java:304)
    at org.ops4j.pax.web.utils.ClassPathUtil.getBundlesInClassSpace(ClassPathUtil.java:304)
    at org.ops4j.pax.web.utils.ClassPathUtil.getBundlesInClassSpace(ClassPathUtil.java:304)
    at org.ops4j.pax.web.utils.ClassPathUtil.getBundlesInClassSpace(ClassPathUtil.java:304)
    at org.ops4j.pax.web.utils.ClassPathUtil.getBundlesInClassSpace(ClassPathUtil.java:304)
    at org.ops4j.pax.web.utils.ClassPathUtil.getBundlesInClassSpace(ClassPathUtil.java:304)
    at org.ops4j.pax.web.extender.war.internal.model.BundleWebApplicationClassSpace.initialize(BundleWebApplicationClassSpace.java:380)
    at org.ops4j.pax.web.extender.war.internal.model.BundleWebApplication.processMetadata(BundleWebApplication.java:1076)
    at org.ops4j.pax.web.extender.war.internal.model.BundleWebApplication.deploy(BundleWebApplication.java:652)
      - locked org.ops4j.pax.web.extender.war.internal.model.BundleWebApplication@4d29e9de
    at org.ops4j.pax.web.extender.war.internal.model.BundleWebApplication$$Lambda$1110/0x00000007cd337798.run(Unknown Source)
    at java.base@17.0.4/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
    at java.base@17.0.4/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base@17.0.4/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
    at java.base@17.0.4/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.base@17.0.4/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.base@17.0.4/java.lang.Thread.run(Thread.java:833)

    Locked synchronizers: count = 1
      - java.util.concurrent.ThreadPoolExecutor$Worker@41b8b6ae
```
Also debugged in but did not get what happens.
For me it looks like the bundles in BundleWebApplicationClassSpace will never get empty and therefore it loops all the time.
Does someone have a hint for me or could check if this is a bug?

Best regards,
Mathias

**Comment by grgrzybek** [comment]
Does it ever end? I've added few complex WABs to Pax Web's tests (like the one with primefaces or vaadin), but there were no problems with endless scanning...

If you enable DEBUG logging for `org.ops4j.pax.web.extender.war`, you should see more information about which _reachable_ bundles (by OSGI wiring or WAR embedding) are scanned.

May I see the WAB you're trying to deploy?

**Comment by swaninga** [comment]
Thanks for the quick answer.
I now enabled TRACE logs and see a lot of wired bundle checks. It doesn't seem to stuck but get slower and slower.

wab-extender-1-thread-3  [org.ops4j.pax.web.pax-web-extender-war:8.0.6]	 Checking wired bundle ...

I generated a heap dump and will analyse it with my colleagues. Maybe a problem in our platform.
I let you know as soon as i have further informations.

**Comment by grgrzybek** [comment]
When running sample test from Pax Web test suite, at DEBUG/TRACE level you can see something like this:
```
08:07:18.614 [wab-extender-2-thread-1] DEBUG (BundleWebApplication.java:1075) org.ops4j.pax.web.extender.war.internal.model.BundleWebApplication - Searching for web fragments
08:07:18.614 [wab-extender-2-thread-1] TRACE (BundleWebApplicationClassSpace.java:284) org.ops4j.pax.web.extender.war.internal.model.BundleWebApplicationClassSpace - Searching for web fragments in WAB Bundle-ClassPath jars
08:07:18.621 [wab-extender-2-thread-1] TRACE (BundleWebApplicationClassSpace.java:287) org.ops4j.pax.web.extender.war.internal.model.BundleWebApplicationClassSpace -   Checking embedded jar jar:bundle://52.0:0/WEB-INF/lib/myfaces-api-2.3.9.jar!/
08:07:18.641 [wab-extender-2-thread-1] TRACE (BundleWebApplicationClassSpace.java:476) org.ops4j.pax.web.extender.war.internal.model.BundleWebApplicationClassSpace -     Found web fragment without descriptor, url: jar:bundle://52.0:0/WEB-INF/lib/myfaces-api-2.3.9.jar!/, jarName: myfaces-api-2.3.9.jar
08:07:18.641 [wab-extender-2-thread-1] TRACE (BundleWebApplicationClassSpace.java:287) org.ops4j.pax.web.extender.war.internal.model.BundleWebApplicationClassSpace -   Checking embedded jar jar:bundle://52.0:0/WEB-INF/lib/myfaces-impl-2.3.9.jar!/
08:07:18.667 [wab-extender-2-thread-1] TRACE (BundleWebApplicationClassSpace.java:471) org.ops4j.pax.web.extender.war.internal.model.BundleWebApplicationClassSpace -     Found web fragment with descriptor, name: myfaces_core, url: jar:bundle://52.0:0/WEB-INF/lib/myfaces-impl-2.3.9.jar!/, jarName: myfaces-impl-2.3.9.jar
08:07:18.668 [wab-extender-2-thread-1] TRACE (BundleWebApplicationClassSpace.java:287) org.ops4j.pax.web.extender.war.internal.model.BundleWebApplicationClassSpace -   Checking embedded jar jar:bundle://52.0:0/WEB-INF/lib/commons-beanutils-1.9.4.jar!/
08:07:18.668 [wab-extender-2-thread-1] TRACE (BundleWebApplicationClassSpace.java:478) org.ops4j.pax.web.extender.war.internal.model.BundleWebApplicationClassSpace -     Skipped web fragment, url: jar:bundle://52.0:0/WEB-INF/lib/commons-beanutils-1.9.4.jar!/, jarName: commons-beanutils-1.9.4.jar
08:07:18.668 [wab-extender-2-thread-1] TRACE (BundleWebApplicationClassSpace.java:287) org.ops4j.pax.web.extender.war.internal.model.BundleWebApplicationClassSpace -   Checking embedded jar jar:bundle://52.0:0/WEB-INF/lib/commons-collections-3.2.2.jar!/
08:07:18.668 [wab-extender-2-thread-1] TRACE (BundleWebApplicationClassSpace.java:478) org.ops4j.pax.web.extender.war.internal.model.BundleWebApplicationClassSpace -     Skipped web fragment, url: jar:bundle://52.0:0/WEB-INF/lib/commons-collections-3.2.2.jar!/, jarName: commons-collections-3.2.2.jar
08:07:18.668 [wab-extender-2-thread-1] TRACE (BundleWebApplicationClassSpace.java:287) org.ops4j.pax.web.extender.war.internal.model.BundleWebApplicationClassSpace -   Checking embedded jar jar:bundle://52.0:0/WEB-INF/lib/commons-digester-1.8.1.jar!/
08:07:18.669 [wab-extender-2-thread-1] TRACE (BundleWebApplicationClassSpace.java:478) org.ops4j.pax.web.extender.war.internal.model.BundleWebApplicationClassSpace -     Skipped web fragment, url: jar:bundle://52.0:0/WEB-INF/lib/commons-digester-1.8.1.jar!/, jarName: commons-digester-1.8.1.jar
08:07:18.669 [wab-extender-2-thread-1] TRACE (BundleWebApplicationClassSpace.java:307) org.ops4j.pax.web.extender.war.internal.model.BundleWebApplicationClassSpace - Searching for web fragments in WAB bundle fragments
08:07:18.669 [wab-extender-2-thread-1] TRACE (BundleWebApplicationClassSpace.java:335) org.ops4j.pax.web.extender.war.internal.model.BundleWebApplicationClassSpace - Searching for web fragments in WAB wired bundles
08:07:18.671 [wab-extender-2-thread-1] TRACE (BundleWebApplicationClassSpace.java:390) org.ops4j.pax.web.extender.war.internal.model.BundleWebApplicationClassSpace -   Checking wired bundle org.ops4j.pax.web.pax-web-jsp [41]
08:07:18.673 [wab-extender-2-thread-1] TRACE (BundleWebApplicationClassSpace.java:541) org.ops4j.pax.web.extender.war.internal.model.BundleWebApplicationClassSpace -     Found web fragment without descriptor, url: bundle://41.0:0/, jarName: org.ops4j.pax.web.pax-web-jsp-8.0.7.SNAPSHOT.bundle
08:07:18.673 [wab-extender-2-thread-1] TRACE (BundleWebApplicationClassSpace.java:374) org.ops4j.pax.web.extender.war.internal.model.BundleWebApplicationClassSpace -   Skipped checking of wired bundle org.eclipse.jdt.core.compiler.batch [40]
08:07:18.673 [wab-extender-2-thread-1] TRACE (BundleWebApplicationClassSpace.java:374) org.ops4j.pax.web.extender.war.internal.model.BundleWebApplicationClassSpace -   Skipped checking of wired bundle org.ops4j.pax.web.pax-web-tomcat-common [24]
08:07:18.674 [wab-extender-2-thread-1] TRACE (BundleWebApplicationClassSpace.java:374) org.ops4j.pax.web.extender.war.internal.model.BundleWebApplicationClassSpace -   Skipped checking of wired bundle org.ops4j.pax.logging.pax-logging-api [14]
08:07:18.674 [wab-extender-2-thread-1] TRACE (BundleWebApplicationClassSpace.java:374) org.ops4j.pax.web.extender.war.internal.model.BundleWebApplicationClassSpace -   Skipped checking of wired bundle jakarta.annotation-api [17]
08:07:18.674 [wab-extender-2-thread-1] TRACE (BundleWebApplicationClassSpace.java:374) org.ops4j.pax.web.extender.war.internal.model.BundleWebApplicationClassSpace -   Skipped checking of wired bundle javax.websocket-api [42]
08:07:18.674 [wab-extender-2-thread-1] TRACE (BundleWebApplicationClassSpace.java:374) org.ops4j.pax.web.extender.war.internal.model.BundleWebApplicationClassSpace -   Skipped checking of wired bundle org.ops4j.pax.web.pax-web-spi [21]
08:07:18.674 [wab-extender-2-thread-1] TRACE (BundleWebApplicationClassSpace.java:374) org.ops4j.pax.web.extender.war.internal.model.BundleWebApplicationClassSpace -   Skipped checking of wired bundle javax.el-api [38]
08:07:18.674 [wab-extender-2-thread-1] TRACE (BundleWebApplicationClassSpace.java:374) org.ops4j.pax.web.extender.war.internal.model.BundleWebApplicationClassSpace -   Skipped checking of wired bundle jakarta.servlet-api [19]
08:07:18.674 [wab-extender-2-thread-1] TRACE (BundleWebApplicationClassSpace.java:374) org.ops4j.pax.web.extender.war.internal.model.BundleWebApplicationClassSpace -   Skipped checking of wired bundle org.ops4j.pax.web.pax-web-api [20]
08:07:18.677 [wab-extender-2-thread-1] DEBUG (BundleWebApplication.java:1088) org.ops4j.pax.web.extender.war.internal.model.BundleWebApplication - Searching for ServletContainerInitializers (SCIs)
...
08:07:18.708 [wab-extender-2-thread-1] TRACE (BundleWebApplicationClassSpace.java:934) org.ops4j.pax.web.extender.war.internal.model.BundleWebApplicationClassSpace - Scanning classes in ordered fragments
08:07:18.709 [wab-extender-2-thread-1] TRACE (BundleWebApplicationClassSpace.java:957) org.ops4j.pax.web.extender.war.internal.model.BundleWebApplicationClassSpace -   Skipping ordered fragment commons-digester-1.8.1.jar (by configuration)
08:07:18.709 [wab-extender-2-thread-1] TRACE (BundleWebApplicationClassSpace.java:957) org.ops4j.pax.web.extender.war.internal.model.BundleWebApplicationClassSpace -   Skipping ordered fragment commons-collections-3.2.2.jar (by configuration)
08:07:18.709 [wab-extender-2-thread-1] TRACE (BundleWebApplicationClassSpace.java:957) org.ops4j.pax.web.extender.war.internal.model.BundleWebApplicationClassSpace -   Skipping ordered fragment commons-beanutils-1.9.4.jar (by configuration)
08:07:18.709 [wab-extender-2-thread-1] TRACE (BundleWebApplicationClassSpace.java:963) org.ops4j.pax.web.extender.war.internal.model.BundleWebApplicationClassSpace -   Scanning ordered fragment myfaces-api-2.3.9.jar, jar:bundle://52.0:0/WEB-INF/lib/myfaces-api-2.3.9.jar!/ (WAB)
08:07:18.752 [wab-extender-2-thread-1] TRACE (BundleWebApplicationClassSpace.java:993) org.ops4j.pax.web.extender.war.internal.model.BundleWebApplicationClassSpace -     Scanning jar:bundle://52.0:0/WEB-INF/lib/myfaces-api-2.3.9.jar!/javax/faces/view/BehaviorHolderAttachedObjectTarget.class
08:07:18.752 [wab-extender-2-thread-1] TRACE (BundleWebApplicationClassSpace.java:993) org.ops4j.pax.web.extender.war.internal.model.BundleWebApplicationClassSpace -     Scanning jar:bundle://52.0:0/WEB-INF/lib/myfaces-api-2.3.9.jar!/javax/faces/view/ValueHolderAttachedObjectHandler.class
08:07:18.753 [wab-extender-2-thread-1] TRACE (BundleWebApplicationClassSpace.java:993) org.ops4j.pax.web.extender.war.internal.model.BundleWebApplicationClassSpace -     Scanning jar:bundle://52.0:0/WEB-INF/lib/myfaces-api-2.3.9.jar!/javax/faces/view/AttachedObjectHandler.class
08:07:18.753 [wab-extender-2-thread-1] TRACE (BundleWebApplicationClassSpace.java:993) org.ops4j.pax.web.extender.war.internal.model.BundleWebApplicationClassSpace -     Scanning jar:bundle://52.0:0/WEB-INF/lib/myfaces-api-2.3.9.jar!/javax/faces/view/ValueHolderAttachedObjectTarget.class
...
08:07:18.874 [wab-extender-2-thread-1] TRACE (BundleWebApplicationClassSpace.java:993) org.ops4j.pax.web.extender.war.internal.model.BundleWebApplicationClassSpace -     Scanning jar:bundle://52.0:0/WEB-INF/lib/myfaces-api-2.3.9.jar!/javax/faces/component/_UISelectItem.class
08:07:18.875 [wab-extender-2-thread-1] TRACE (BundleWebApplicationClassSpace.java:1100) org.ops4j.pax.web.extender.war.internal.model.BundleWebApplicationClassSpace -       Loading javax.faces.component._UISelectItem, using org.ops4j.pax.web.samples.war-jsf23-embedded [52]
08:07:18.875 [wab-extender-2-thread-1] TRACE (BundleWebApplicationClassSpace.java:993) org.ops4j.pax.web.extender.war.internal.model.BundleWebApplicationClassSpace -     Scanning jar:bundle://52.0:0/WEB-INF/lib/myfaces-api-2.3.9.jar!/javax/faces/component/UIComponent$1.class
08:07:18.875 [wab-extender-2-thread-1] TRACE (BundleWebApplicationClassSpace.java:993) org.ops4j.pax.web.extender.war.internal.model.BundleWebApplicationClassSpace -     Scanning jar:bundle://52.0:0/WEB-INF/lib/myfaces-api-2.3.9.jar!/javax/faces/component/UIOutput.class
08:07:18.876 [wab-extender-2-thread-1] TRACE (BundleWebApplicationClassSpace.java:1100) org.ops4j.pax.web.extender.war.internal.model.BundleWebApplicationClassSpace -       Loading javax.faces.component.UIOutput, using org.ops4j.pax.web.samples.war-jsf23-embedded [52]
...
08:07:19.147 [wab-extender-2-thread-1] TRACE (BundleWebApplicationClassSpace.java:963) org.ops4j.pax.web.extender.war.internal.model.BundleWebApplicationClassSpace -   Scanning ordered fragment myfaces-impl-2.3.9.jar, jar:bundle://52.0:0/WEB-INF/lib/myfaces-impl-2.3.9.jar!/ (WAB)
08:07:19.177 [wab-extender-2-thread-1] TRACE (BundleWebApplicationClassSpace.java:993) org.ops4j.pax.web.extender.war.internal.model.BundleWebApplicationClassSpace -     Scanning jar:bundle://52.0:0/WEB-INF/lib/myfaces-impl-2.3.9.jar!/org/apache/myfaces/view/ViewScopeProxyMap.class
08:07:19.177 [wab-extender-2-thread-1] TRACE (BundleWebApplicationClassSpace.java:993) org.ops4j.pax.web.extender.war.internal.model.BundleWebApplicationClassSpace -     Scanning jar:bundle://52.0:0/WEB-INF/lib/myfaces-impl-2.3.9.jar!/org/apache/myfaces/view/ViewScopeProxyMap$1.class
...
08:07:19.484 [wab-extender-2-thread-1] TRACE (BundleWebApplicationClassSpace.java:963) org.ops4j.pax.web.extender.war.internal.model.BundleWebApplicationClassSpace -   Scanning ordered fragment org.ops4j.pax.web.pax-web-jsp-8.0.7.SNAPSHOT.bundle, bundle://41.0:0/ (container)
08:07:19.488 [wab-extender-2-thread-1] TRACE (BundleWebApplicationClassSpace.java:993) org.ops4j.pax.web.extender.war.internal.model.BundleWebApplicationClassSpace -     Scanning bundle://41.0:0/javax/servlet/jsp/ErrorData.class
08:07:19.488 [wab-extender-2-thread-1] TRACE (BundleWebApplicationClassSpace.java:993) org.ops4j.pax.web.extender.war.internal.model.BundleWebApplicationClassSpace -     Scanning bundle://41.0:0/javax/servlet/jsp/HttpJspPage.class
...
08:07:19.632 [wab-extender-2-thread-1] DEBUG (BundleWebApplication.java:1259) org.ops4j.pax.web.extender.war.internal.model.BundleWebApplication - Finished metadata and fragment processing for org.ops4j.pax.web.samples.war-jsf23-embedded [52] in 1084ms
```

You can see the information of all scanned jars and (at TRACE level) even the classes.

With #1653 I've added a way to configure "skipped jars" bundle context (not PID!) property. By default, `org.ops4j.pax.web.extender.war.jarsToSkip` is configured with this complex list:
```java
DEFAULT_IGNORED_LIBRARIES = Arrays.asList(
		"javax.*",
		"jakarta.*",
		"org.apache.aries.*", // as bundle
		"org.apache.aries.*.jar", // as embedded jar (in hawtio for example)
		"org.apache.felix.*",
		"org.apache.karaf.*",
		"org.osgi.util.*",
		"org.ops4j.pax.logging.*",
		"org.ops4j.pax.web.pax-web-api",
		"org.ops4j.pax.web.pax-web-spi",
		"org.ops4j.pax.web.pax-web-runtime",
		"org.ops4j.pax.web.pax-web-extender-*",
		"org.ops4j.pax.web.pax-web-karaf",
		"org.ops4j.pax.web.pax-web-jetty*",
		"org.ops4j.pax.web.pax-web-tomcat",
		"org.ops4j.pax.web.pax-web-tomcat-common",
		"org.ops4j.pax.web.pax-web-undertow",
		"org.eclipse.jdt.core.compiler.batch",
		// see Tomcat's tomcat.util.scan.StandardJarScanFilter.jarsToSkip property in
		// TOMCAT_HOME/conf/catalina.properties
		"annotations-api.jar",
		"ant*.jar",
		"asm*.jar",
		"aspectj*.jar",
		"cglib*.jar",
		"cobertura*.jar",
		"org.apache.commons.*", // as bundle
		"commons-*.jar", // as embedded jar
		"dom4j-*.jar",
		"easymock-*.jar",
		"ecj-*.jar",
		"el-api.jar",
		"geronimo-spec-*.jar",
		"guava-*.jar",
		"h2*.jar",
		"hamcrest*.jar",
		"hibernate*.jar",
		"httpcore*.jar",
		"httpclient*.jar",
		"icu4j-*.jar",
		"jackson-*.jar",
		"jasper-el.jar",
		"jasper.jar",
		"jaspic-api.jar",
		"jaxb-*.jar",
		"jaxen-*.jar",
		"jdom-*.jar",
		"jetty-*.jar",
		"jmx-tools.jar",
		"jmx.jar",
		"jolokia-*.jar",
		"jsp-api.jar",
		"jstl.jar",
		"jta*.jar",
		"junit-*.jar",
		"junit.jar",
		"log4j*.jar",
		"mail*.jar",
		"objenesis-*.jar",
		"oraclepki.jar",
		"oro-*.jar",
		"servlet-api-*.jar",
		"servlet-api.jar",
		"slf4j*.jar",
		"swagger-*.jar",
		"taglibs-standard-spec-*.jar",
		"tagsoup-*.jar",
		"tools.jar",
		"websocket-api.jar",
		"wsdl4j*.jar",
		"xercesImpl.jar",
		"xml-apis.jar",
		"xmlParserAPIs-*.jar",
		"xmlParserAPIs.jar",
		"xom-*.jar"
);
```

You can create your own set of skipped jars/bundles to scan - if you include `default` value (literally) in the comma separated list, all of the above will be included.

This list matches what we know from Tomcat configuration in `CATALINA_HOME/conf/catalina.properties` file, `tomcat.util.scan.StandardJarScanFilter.jarsToSkip` property.

**Comment by swaninga** [comment]
Thanks for that hint with the jarsToSkip. I will try that but it will take some time.
Btw, if i set the system property for example as
org.ops4j.pax.web.extender.war.jarsToSkip = io.netty.buffer,default
that doesn't seem to work.
Should the regex you are using be "\\s*,\\s*" instead of "\\s*,\\s" ? (with an additional asterix at the end)

**Comment by grgrzybek** [comment]
Good catch @swaninga ! I fixed the split regexp.

`org.ops4j.pax.web.extender.war.jarsToSkip` should be a _context property_ (in Karaf - `etc/config.properties` or `etc/custom.properties`), not a system property...

**Comment by grgrzybek** [comment]
for now, you'd have to use `io.netty.buffer, default` (with one space after comma).

**Comment by swaninga** [comment]
Just a short update. 
I added some logs to understand what happens in my environment and saw that the bundles deque has hundred of thousands bundles.
Many of the bundles are inside a multiple time.
Maybe there is some kind of circularity in our platform but it is hard to find because we use a lot of bundles.
Anyway, i tried a workaround and changed the following code by adding the !bundles.contains(rb) condition.

Set<Bundle> reachable = new HashSet<>();
ClassPathUtil.getBundlesInClassSpace(scannedBundle, reachable);
for (Bundle rb : reachable) {
	if (!processedBundles.contains(rb) && !Utils.isFragment(rb) **&& !bundles.contains(rb)**) {
	      bundles.add(rb);
	}
}

Not sure if this is valid and if my wabClassLoader is complete but at the end everything will be deployed and i can continue testing our integration.
Will come back later and try to find some suspicous bundles in our platform that should be skipped.

**Comment by grgrzybek** [comment]
If the above fragment works for you, I can use it to speed up the process - surely, when I was rewriting this scanning part, `processedBundles` was all I needed, but I can imagine that real-life scenario may be much bigger.

With bundles, the "closure" can be very big (when including wired packages, embedded and required bundles). Thanks for spotting!
