### ISSUE TITLE
jetty-bundle - issues 

### ISSUE THREAD

**Issue by rimmeraj** [ops4j/org.ops4j.pax.web#1763]
On version 8.0.9 the bundle contains

META-INF/services/org.eclipse.jetty.security.Authenticator$Factory

This load loads the jetty-jaspi which is not in the bundle and you get an ClassNotFound exception. I did
zip -d pax-web-jetty-bundle-8.0.9.jar META-INF/services/org.eclipse.jetty.security.Authenticator\$Factory

to remove the entry and the bundle works fine now.

**Comment by grgrzybek** [comment]
Hmm, the same was with earlier Pax Web 8 versions. May I ask for a stack trace where this happens? Is it enough just to install the bundle?
I always preferred to use the bundles separately, but there are tests for pax-web-jetty-bundle (same for Tomcat and Undertow versions) and I definitely don't include Jaspi jars...

**Comment by rimmeraj** [comment]
[paxweb-config-1-thread-1] WARN org.eclipse.jetty.security.SecurityHandler - Error while loading AuthenticatorFactory with ServiceLoader
java.util.ServiceConfigurationError: org.eclipse.jetty.security.Authenticator$Factory: org.eclipse.jetty.security.jaspi.JaspiAuthenticatorFactory Unable to get public no-arg constructor
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:586)
	at java.base/java.util.ServiceLoader.getConstructor(ServiceLoader.java:679)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1240)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393)
	at org.eclipse.jetty.security.SecurityHandler.<clinit>(SecurityHandler.java:86)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.eclipse.jetty.servlet.ServletContextHandler.newSecurityHandler(ServletContextHandler.java:331)
	at org.eclipse.jetty.servlet.ServletContextHandler.getSecurityHandler(ServletContextHandler.java:396)
	at org.eclipse.jetty.servlet.ServletContextHandler.relinkHandlers(ServletContextHandler.java:240)
	at org.eclipse.jetty.servlet.ServletContextHandler.<init>(ServletContextHandler.java:162)
	at org.eclipse.jetty.servlet.ServletContextHandler.<init>(ServletContextHandler.java:131)
	at org.eclipse.jetty.servlet.ServletContextHandler.<init>(ServletContextHandler.java:136)
	at org.ops4j.pax.web.service.jetty.internal.PaxWebServletContextHandler.<init>(PaxWebServletContextHandler.java:105)
	at org.ops4j.pax.web.service.jetty.internal.JettyServerWrapper.visitServletContextModelChange(JettyServerWrapper.java:761)
	at org.ops4j.pax.web.service.spi.task.ServletContextModelChange.accept(ServletContextModelChange.java:47)
	at org.ops4j.pax.web.service.spi.task.Batch.accept(Batch.java:430)
	at org.ops4j.pax.web.service.jetty.internal.JettyServerController.sendBatch(JettyServerController.java:168)
	at org.ops4j.pax.web.service.internal.HttpServiceEnabled$WhiteboardWebContainer.lambda$addWhiteboardOsgiContextModel$0(HttpServiceEnabled.java:2259)
	at org.ops4j.pax.web.service.spi.model.ServerModel.lambda$run$2(ServerModel.java:540)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NoClassDefFoundError: javax/security/auth/message/AuthException
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3373)
	at java.base/java.lang.Class.getConstructor0(Class.java:3578)
	at java.base/java.lang.Class.getConstructor(Class.java:2271)
	at java.base/java.util.ServiceLoader$1.run(ServiceLoader.java:666)
	at java.base/java.util.ServiceLoader$1.run(ServiceLoader.java:663)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at java.base/java.util.ServiceLoader.getConstructor(ServiceLoader.java:674)
	... 30 more
Caused by: java.lang.ClassNotFoundException: javax.security.auth.message.AuthException cannot be found by org.ops4j.pax.web.pax-web-jetty-bundle_8.0.9
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:506)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:170)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 38 more

**Comment by grgrzybek** [comment]
Thanks - I'll handle that. Looks like the application proceeds fine then, right?

**Comment by grgrzybek** [comment]
No problems in `HttpServiceJettyBundleIntegrationTest`... Checking further.

**Comment by grgrzybek** [comment]
I checked with Whiteboard scenario (new test), but still - even if `pax-web-jetty-bundle` contains `/META-INF/services/org.eclipse.jetty.security.Authenticator$Factory` service, it's not found in my scenario - `java.util.ServiceLoader#load(java.lang.Class<S>)` is used which uses TCCL, which is set to platform classloader, which can't return any `/META-INF/services/org.eclipse.jetty.security.Authenticator$Factory`...

Is there a chance you debug this call and check what's the TCCL passed to `java.util.ServiceLoader#load()`? Maybe you put pax-web-jetty-bundle to non-OSGi classpath?

What is the runtime you're using - Karaf? Felix/Equinox alone?

**Comment by grgrzybek** [comment]
Nevertheless, I've removed `/META-INF/services/org.eclipse.jetty.security.Authenticator$Factory` and `org/eclipse/jetty/security/jaspi` from pax-web-jetty-bundle entirely.

But I'm still curious about your setup.
