### ISSUE TITLE
[8.0.x] Issues when using Whiteboard context that overrides "default", "/" context

### ISSUE THREAD

**Issue by grgrzybek** [ops4j/org.ops4j.pax.web#1769]
See the discussion at https://groups.google.com/g/ops4j/c/TiQ3g4-Dan4

**Comment by rimmeraj** [comment]
As I suspected it is a timing issue. Adding the debugging it works sometime and fails sometime. Here are two logs one showing each case
[debug.good.txt](https://github.com/ops4j/org.ops4j.pax.web/files/9607153/debug.good.txt)
[degug.fail.txt](https://github.com/ops4j/org.ops4j.pax.web/files/9607155/degug.fail.txt)

**Comment by grgrzybek** [comment]
OK, here's something.

**debug.good.txt**:
```
[paxweb-config-1-thread-1] DEBUG org.ops4j.pax.web.service.internal.WebElementEventDispatcher - Sending web element event FAILED (com.candatag.repository/1.0.7): org.ops4j.pax.web.service.spi.model.events.ServletEventData@35d12290 Cannot invoke "org.ops4j.pax.web.service.spi.servlet.OsgiServletContext.getOsgiContextModel()" because "osgiContext" is null for bundle com.candatag.repository
[paxweb-config-1-thread-1] DEBUG org.ops4j.pax.web.service.internal.WebElementEventDispatcher - Sending web element event FAILED (com.candatag.repository/1.0.7): org.ops4j.pax.web.service.spi.model.events.ServletEventData@16885e3 Cannot invoke "org.ops4j.pax.web.service.spi.servlet.OsgiServletContext.getOsgiContextModel()" because "osgiContext" is null for bundle com.candatag.repository
```

**debug.fail.txt**:
```
[paxweb-config-1-thread-1] DEBUG org.ops4j.pax.web.service.internal.WebElementEventDispatcher - Sending web element event FAILED (com.candatag.repository/1.0.7): org.ops4j.pax.web.service.spi.model.events.ServletEventData@23e37c86 Cannot invoke "org.ops4j.pax.web.service.spi.servlet.OsgiServletContext.getOsgiContextModel()" because "osgiContext" is null for bundle com.candatag.repository
[paxweb-config-1-thread-1] DEBUG org.ops4j.pax.web.service.internal.WebElementEventDispatcher - Sending web element event FAILED (com.candatag.repository/1.0.7): org.ops4j.pax.web.service.spi.model.events.ServletEventData@40cf748f Cannot invoke "org.ops4j.pax.web.service.spi.servlet.OsgiServletContext.getOsgiContextModel()" because "osgiContext" is null for bundle com.candatag.repository
[paxweb-config-1-thread-1] DEBUG org.ops4j.pax.web.service.internal.WebElementEventDispatcher - Sending web element event FAILED (com.candatag.k8s/1.0.5): org.ops4j.pax.web.service.spi.model.events.ServletEventData@6e05e4fb Cannot invoke "org.ops4j.pax.web.service.spi.servlet.OsgiServletContext.getOsgiContextModel()" because "osgiContext" is null for bundle com.candatag.k8s
```

**Comment by rimmeraj** [comment]
Where is the code where the registered servlet decides which context to add to?
Were is the code that new ServletContextHelpers get registered. My guess is that a a Map of Contexts is getting updated before the context is finished being initialized.

**Comment by grgrzybek** [comment]
A `javax.servlet.Servlet` OSGi service is registered and it's being tracked by `org.ops4j.pax.web.extender.whiteboard.internal.tracker.ServletTracker`.

Then legacy `httpContext.id` or standard `osgi.http.whiteboard.context.select` service registration properties are checked to decide which contexts we're targetting (by names, not instances).

If neither is present, default _selector_ is used: `(osgi.http.whiteboard.context.name=default)`.

This selector is used as filter declaration to `org.osgi.framework.BundleContext#createFilter()`. Resulting filter is used to match against all (currently) available contexts:
* from `org.ops4j.pax.web.extender.whiteboard.internal.WhiteboardExtenderContext#osgiContextsList` - the Whiteboard map
* contexts which are not Whiteboard ones (maybe from WABs or HttpService)

Resulting list of instances is associated with the Servlet being registered (in the form of `org.ops4j.pax.web.service.spi.model.elements.ServletModel` internal class).

As we've found out previously - looks like your servlets are being processed with context instances (resolved using the above mentioned filters/selectors) which are not yet passed to Jetty/Tomcat/Undertow. Checking this path.

**Comment by grgrzybek** [comment]
And again - this is the same situation. First a servlet is registered even before the web container. It references `OCM-2`:
```
[main] DEBUG org.ops4j.pax.web.extender.whiteboard.internal.BundleWhiteboardApplication - ServletModel{id=ServletModel-4,name='com.candatag.k8s.zoo.servlet.ReadyProbe',urlPatterns=[/osgi/started],contexts=[{WB,OCM-2,default,/}]} will be registered when WebContainer/HttpService is available
```

then the container is available, so the registration proceeds:
```
[HttpService->Whiteboard (add HttpService)] DEBUG org.ops4j.pax.web.service.internal.HttpServiceEnabled - Passing registration of ServletModel{id=ServletModel-4,name='com.candatag.k8s.zoo.servlet.ReadyProbe',urlPatterns=[/osgi/started],contexts=[{WB,OCM-2,default,/}]} to configuration thread
```

but only later the `OCM-2` itself is processed:
```
[paxweb-config-1-thread-1] INFO org.ops4j.pax.web.service.jetty.internal.JettyServerController - Receiving Batch{"Registration of OsgiContextModel{WB,id=OCM-2,name='default',path='/',bundle=com.candatag.web.util,ref={org.osgi.service.http.context.ServletContextHelper}={service.id=56, osgi.http.whiteboard.context.name=default, service.bundleid=19, service.scope=bundle, service.ranking=2147483647, component.name=com.candatag.web.util.zoo.impl.NoSecurityContextImpl, osgi.http.whiteboard.context.path=/, component.id=21}}", size=1}
[paxweb-config-1-thread-1] INFO org.ops4j.pax.web.service.jetty.internal.JettyServerWrapper - Adding OsgiContextModel{WB,id=OCM-2,name='default',path='/',bundle=com.candatag.web.util,ref={org.osgi.service.http.context.ServletContextHelper}={service.id=56, osgi.http.whiteboard.context.name=default, service.bundleid=19, service.scope=bundle, service.ranking=2147483647, component.name=com.candatag.web.util.zoo.impl.NoSecurityContextImpl, osgi.http.whiteboard.context.path=/, component.id=21}} to o.o.p.w.s.j.i.PaxWebServletContextHandler@75c097c6{/,null,STOPPED}
```

looks like you're using SCR for the context (`component.id=21` property) and for the servlet (`component.id=5`). May I see the annotations on these two?

**Comment by grgrzybek** [comment]
one more thing - is it Equinox or Felix?
and what are the bundle ids and start levels of:
* the bundle registering the servlet
* the bundle registering the context
* the bundle with SCR implementation (felix.scr?)

**Comment by rimmeraj** [comment]
More checking of the log, the start order of the bundles does not change from success to failure. They are listed in the same order. Is not the issue you are adding a a context into WhiteboardExtenderContext that is not completely initialized ? Should it not be registered first and then added to the context?

**Comment by grgrzybek** [comment]
"Registration" of the servlet context in OSGi registry is only a decoration - I don't really see any usefulness of it exception satisfying the specification. So it doesn't matter here.

**Comment by grgrzybek** [comment]
I have two threads:

registration of the servlet:
```
"Thread-2@4595" prio=5 tid=0x24 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at org.ops4j.pax.web.extender.whiteboard.internal.WhiteboardExtenderContext.resolveContexts(WhiteboardExtenderContext.java:240)
	  at org.ops4j.pax.web.extender.whiteboard.internal.tracker.AbstractElementTracker.addingService(AbstractElementTracker.java:250)
	  at org.ops4j.pax.web.extender.whiteboard.internal.tracker.AbstractElementTracker.addingService(AbstractElementTracker.java:185)
	  at org.ops4j.pax.web.extender.whiteboard.internal.tracker.AbstractElementTracker.addingService(AbstractElementTracker.java:62)
	  at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:941)
	  at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:870)
	  at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256)
	  at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229)
	  at org.osgi.util.tracker.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:901)
	  at org.apache.felix.framework.EventDispatcher.invokeServiceListenerCallback(EventDispatcher.java:990)
	  at org.apache.felix.framework.EventDispatcher.fireEventImmediately(EventDispatcher.java:838)
	  at org.apache.felix.framework.EventDispatcher.fireServiceEvent(EventDispatcher.java:545)
	  at org.apache.felix.framework.Felix.fireServiceEvent(Felix.java:4595)
	  at org.apache.felix.framework.Felix.registerService(Felix.java:3587)
	  at org.apache.felix.framework.BundleContextImpl.registerService(BundleContextImpl.java:348)
	  at org.apache.felix.framework.BundleContextImpl.registerService(BundleContextImpl.java:355)
	  at org.ops4j.pax.web.extender.samples.whiteboard.internal.Activator.lambda$start$0(Activator.java:47)
	  at org.ops4j.pax.web.extender.samples.whiteboard.internal.Activator$$Lambda$80.296541232.run(Unknown Source:-1)
	  at java.lang.Thread.run(Thread.java:750)
```

registration of the context:
```
"Thread-10@4810" prio=5 tid=0x2e nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at org.ops4j.pax.web.extender.whiteboard.internal.WhiteboardExtenderContext.addWebContext(WhiteboardExtenderContext.java:383)
	  at org.ops4j.pax.web.extender.whiteboard.internal.tracker.AbstractContextTracker.addingService(AbstractContextTracker.java:154)
	  at org.ops4j.pax.web.extender.whiteboard.internal.tracker.AbstractContextTracker.addingService(AbstractContextTracker.java:50)
	  at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:941)
	  at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:870)
	  at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256)
	  at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229)
	  at org.osgi.util.tracker.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:901)
	  at org.apache.felix.framework.EventDispatcher.invokeServiceListenerCallback(EventDispatcher.java:990)
	  at org.apache.felix.framework.EventDispatcher.fireEventImmediately(EventDispatcher.java:838)
	  at org.apache.felix.framework.EventDispatcher.fireServiceEvent(EventDispatcher.java:545)
	  at org.apache.felix.framework.Felix.fireServiceEvent(Felix.java:4595)
	  at org.apache.felix.framework.Felix.registerService(Felix.java:3587)
	  at org.apache.felix.framework.BundleContextImpl.registerService(BundleContextImpl.java:348)
	  at org.apache.felix.framework.BundleContextImpl.registerService(BundleContextImpl.java:355)
	  at org.ops4j.pax.web.extender.samples.whiteboard.internal.Activator.lambda$start$1(Activator.java:57)
	  at org.ops4j.pax.web.extender.samples.whiteboard.internal.Activator$$Lambda$98.1997357673.run(Unknown Source:-1)
	  at java.lang.Thread.run(Thread.java:750)
```

There's single `org.ops4j.pax.web.extender.whiteboard.internal.WhiteboardExtenderContext#lock` involved, so the synchronization is in place...

I think I got it - there may be a race when registration of the context and the servlet happen before the `HttpService` instance is available. So it should be enough (for me to test) to start the whiteboard bundles before pax-web-jetty bundle.

**Comment by rimmeraj** [comment]
Cool. In my case the whiteboard bundle is before the jetty bundle so it would be starting first

**Comment by grgrzybek** [comment]
@rimmeraj the fix is ready, all tests (including newly added) pass. Here's the most important part of the fix - see the comment which describes (hopefully) your scenario: https://github.com/ops4j/org.ops4j.pax.web/blob/b1cd5b6b92a103afd623f1aff84925fffe6abcb6/pax-web-extender-whiteboard/src/main/java/org/ops4j/pax/web/extender/whiteboard/internal/WhiteboardExtenderContext.java#L263-L279

**Comment by rimmeraj** [comment]
This looks weird ...
https://github.com/ops4j/org.ops4j.pax.web/commit/9d09a8a7b2ef1abb674ab02fa85ac72a06670484

A bit of debugging?

What is the best way to test this?
