### ISSUE TITLE
pax-web-Jetty 7.x imports wrong org.eclipse.jetty.alpn version

### ISSUE THREAD

**Issue by Maurice-Betzel** [ops4j/org.ops4j.pax.web#1801]
Hi, pax-web-Jetty 7.x seems to import the wrong org.eclipse.jetty.alpn:

org.eclipse.jetty.alpn; version="[7.1.0,10.0.0)"; resolution:=optional,

Should this not be org.eclipse.jetty.alpn;version="1.1.3"; resolution:=optional,      ?
And how to get around this, maybe a TCCL switch on init, being called from pax web, of the OpenJDK8ServerALPNProcessor?

**Comment by grgrzybek** [comment]
It was like this since 2015... In dc30b0b47dc59e8b6b3b03c8fc87b69b01dd2dcf.

I see that mvn:org.mortbay.jetty.alpn/alpn-boot/8.1.2.v20141202 is used, not eclipse.jetty.alpn, so the version should be OK...

**Comment by Maurice-Betzel** [comment]
Oha, if i take a look at jetty-osgi-alpn it uses below as dependency, maybe I do not need this fragment on the system bundle?

<alpn.api.version>1.1.3.v20160715</alpn.api.version>

<dependency>
      <groupId>org.eclipse.jetty.alpn</groupId>
      <artifactId>alpn-api</artifactId>
      <version>${alpn.api.version}</version>
      <scope>provided</scope>
    </dependency>

**Comment by grgrzybek** [comment]
Hmm, I recall something about a need to put this bundle/jar to lib/ext (there's a comment in features.xml file):
```xml
    	<details>
    		Please beware, for this feature to run properly you'll need to add the alpn-boot.jar to the
    		lib/ext folder of Karaf in some cases of your JVM.

    		make sure you have the following jar from it's maven coordinate installed:

    		mvn:org.mortbay.jetty.alpn/alpn-boot/8.1.4.v20150727 (and yes version 8.x is intentional there is no newer version available)

    	</details>
```

**Comment by grgrzybek** [comment]
And there's complete rewrite of the http/2 code in Pax Web 8...

**Comment by Maurice-Betzel** [comment]
I need a ALPN processor for dealing with the Lets Encrypt TLS acme-tls/1 challange. So far all is up except pax-web-jetty cannot find my ALPN class:

2022-11-24T14:25:45,774 | ERROR | FelixDispatchQueue | pax-web-jetty                    | 102 - org.ops4j.pax.web.pax-web-jetty - 7.2.10 | FrameworkEvent ERROR - org.ops4j.pax.web.pax-web-jetty
java.lang.NoClassDefFoundError: org/eclipse/jetty/alpn/ALPN
	at eu.abeel.platform.security.acme.service.internal.OpenJDK8ServerALPNProcessor.init(OpenJDK8ServerALPNProcessor.java:26) ~[?:?]
	at eu.abeel.platform.security.acme.api.JettyAlpnServerConnectionFactory$ALPNProcessorServerTracker.addingService(JettyAlpnServerConnectionFactory.java:75) ~[?:?]
	at eu.abeel.platform.security.acme.api.JettyAlpnServerConnectionFactory$ALPNProcessorServerTracker.addingService(JettyAlpnServerConnectionFactory.java:63) ~[?:?]

**Comment by grgrzybek** [comment]
Hmm, you are right about the import version range... But how did it survive like this since 2015?
Did you try Pax Web 8? Which Karaf version do you use? Which JDK?

**Comment by grgrzybek** [comment]
Hmm again. In Pax Web 8, `org.eclipse.jetty.alpn.ALPN` class comes from org/eclipse/jetty/alpn/alpn-api/1.1.3.v20160715/alpn-api-1.1.3.v20160715.jar
In Pax Web 7.2, this class comes from org/mortbay/jetty/alpn/alpn-boot/8.1.2.v20141202/alpn-boot-8.1.2.v20141202.jar

So the versions are correct.

Did you put alpn-boot-8.1.2.v20141202.jar to `lib/ext`?

**Comment by Maurice-Betzel** [comment]
I will create a fragment alla jetty-osgi-alpn and lets see. i still use Karaf 4.2.6 and Java 8, working on adding Apache Avro to Karaf Cellar so the cluster does not rely on the same Java version anymore for serialization. Nearly done with that, then this came along from our operative team, please make the certificate updates automatic :) .

**Comment by Maurice-Betzel** [comment]
Adding the alpn-boot-8xxx to the lib\ext resulted in:

2022-11-24T16:46:40,763 | WARN  | FelixStartLevel  | JettyAlpnServerConnectionFactory | 86 - org.eclipse.jetty.util - 9.4.18.v20190429 | Could not initialize eu.abeel.platform.security.acme.service.internal.OpenJDK8ServerALPNProcessor@149f143
java.lang.IllegalStateException: org.eclipse.jetty.alpn.ALPN must be on JVM boot classpath
	at eu.abeel.platform.security.acme.service.internal.OpenJDK8ServerALPNProcessor.init(OpenJDK8ServerALPNProcessor.java:27) ~[?:?]
	at eu.abeel.platform.security.acme.api.JettyAlpnServerConnectionFactory$ALPNProcessorServerTracker.addingService(JettyAlpnServerConnectionFactory.java:75) [102:org.ops4j.pax.web.pax-web-jetty:7.2.10]
	at eu.abeel.platform.security.acme.api.JettyAlpnServerConnectionFactory$ALPNProcessorServerTracker.addingService(JettyAlpnServerConnectionFactory.java:63) [102:org.ops4j.pax.web.pax-web-jetty:7.2.10]

For Java 8 from 1.8.0_252 and later (including Java 9+) this should not be needed anymore according to Jetty doc.

**Comment by Maurice-Betzel** [comment]
The issue occurs on init of the OpenJDK8ServerALPNProcessor class where ALPN is called:

2022-11-24T16:55:16,486 | DEBUG | paxweb-config-1-thread-1 | JettyServerHandlerCollection     | 102 - org.ops4j.pax.web.pax-web-jetty - 7.2.10 | Adding bean: SecuredRedirectHandler@192037a2{STOPPED}
2022-11-24T16:55:16,487 | DEBUG | paxweb-config-1-thread-1 | JettyServerHandlerCollection     | 102 - org.ops4j.pax.web.pax-web-jetty - 7.2.10 | calling supper add bean ...
2022-11-24T16:55:16,587 | DEBUG | paxweb-config-1-thread-1 | AbstractConnector                | 86 - org.eclipse.jetty.util - 9.4.18.v20190429 | ServerConnector@5c863fa9{SSL,[ssl]}{0.0.0.0:0} added SslConnectionFactory@2ac33b6e{SSL->http/1.1}
2022-11-24T16:55:16,589 | DEBUG | paxweb-config-1-thread-1 | AbstractConnector                | 86 - org.eclipse.jetty.util - 9.4.18.v20190429 | ServerConnector@5c863fa9{SSL,[ssl, http/1.1]}{0.0.0.0:0} added HttpConnectionFactory@6d2afb9[HTTP/1.1]
2022-11-24T16:55:16,600 | DEBUG | paxweb-config-1-thread-1 | JettyAlpnServerConnectionFactory | 86 - org.eclipse.jetty.util - 9.4.18.v20190429 | protocols: [acme-tls/1,  http/1.1]
2022-11-24T16:55:16,602 | DEBUG | paxweb-config-1-thread-1 | AbstractConnector                | 86 - org.eclipse.jetty.util - 9.4.18.v20190429 | ServerConnector@3e3fa5f2{SSL,[ssl]}{0.0.0.0:0} added SslConnectionFactory@5c245fb5{SSL->alpn}
2022-11-24T16:55:16,604 | DEBUG | paxweb-config-1-thread-1 | AbstractConnector                | 86 - org.eclipse.jetty.util - 9.4.18.v20190429 | ServerConnector@3e3fa5f2{SSL,[ssl, alpn]}{0.0.0.0:0} added JettyAlpnServerConnectionFactory@7670b8c{[alpn],http/1.1,[acme-tls/1, http/1.1]}
2022-11-24T16:55:16,605 | DEBUG | paxweb-config-1-thread-1 | AbstractConnector                | 86 - org.eclipse.jetty.util - 9.4.18.v20190429 | ServerConnector@3e3fa5f2{null,[alpn, ssl]}{0.0.0.0:0} removed SslConnectionFactory@5c245fb5{SSL->alpn}
2022-11-24T16:55:16,606 | DEBUG | paxweb-config-1-thread-1 | AbstractConnector                | 86 - org.eclipse.jetty.util - 9.4.18.v20190429 | ServerConnector@3e3fa5f2{SSL,[alpn, ssl]}{0.0.0.0:0} added SslConnectionFactory@495897b{SSL->http/1.1}
2022-11-24T16:55:16,607 | DEBUG | paxweb-config-1-thread-1 | AbstractConnector                | 86 - org.eclipse.jetty.util - 9.4.18.v20190429 | ServerConnector@3e3fa5f2{SSL,[alpn, ssl, http/1.1]}{0.0.0.0:0} added HttpConnectionFactory@4746ac2e[HTTP/1.1]
2022-11-24T16:55:16,610 | DEBUG | paxweb-config-1-thread-1 | AbstractConnector                | 86 - org.eclipse.jetty.util - 9.4.18.v20190429 | ServerConnector@39e19a84{HTTP/1.1,[http/1.1]}{0.0.0.0:0} added HttpConnectionFactory@665dd5f[HTTP/1.1]
2022-11-24T16:55:16,653 | INFO  | FelixStartLevel  | CommandExtension                 | 63 - org.apache.karaf.shell.core - 4.2.6 | Registering commands for bundle org.apache.karaf.event/4.2.6
2022-11-24T16:55:16,666 | INFO  | paxweb-config-1-thread-1 | JettyServerImpl                  | 102 - org.ops4j.pax.web.pax-web-jetty - 7.2.10 | Pax Web available at [0.0.0.0]:[8443]
2022-11-24T16:55:16,666 | INFO  | paxweb-config-1-thread-1 | JettyServerImpl                  | 102 - org.ops4j.pax.web.pax-web-jetty - 7.2.10 | Pax Web available at [0.0.0.0]:[443]
2022-11-24T16:55:16,667 | INFO  | paxweb-config-1-thread-1 | JettyServerImpl                  | 102 - org.ops4j.pax.web.pax-web-jetty - 7.2.10 | Pax Web available at [0.0.0.0]:[80]

**Comment by Maurice-Betzel** [comment]
Without the ALPN proccesor class OpenJDK8ServerALPNProcessor all boots well:

2022-11-24T16:55:16,486 | DEBUG | paxweb-config-1-thread-1 | JettyServerHandlerCollection     | 102 - org.ops4j.pax.web.pax-web-jetty - 7.2.10 | Adding bean: SecuredRedirectHandler@192037a2{STOPPED}
2022-11-24T16:55:16,487 | DEBUG | paxweb-config-1-thread-1 | JettyServerHandlerCollection     | 102 - org.ops4j.pax.web.pax-web-jetty - 7.2.10 | calling supper add bean ...
2022-11-24T16:55:16,587 | DEBUG | paxweb-config-1-thread-1 | AbstractConnector                | 86 - org.eclipse.jetty.util - 9.4.18.v20190429 | ServerConnector@5c863fa9{SSL,[ssl]}{0.0.0.0:0} added SslConnectionFactory@2ac33b6e{SSL->http/1.1}
2022-11-24T16:55:16,589 | DEBUG | paxweb-config-1-thread-1 | AbstractConnector                | 86 - org.eclipse.jetty.util - 9.4.18.v20190429 | ServerConnector@5c863fa9{SSL,[ssl, http/1.1]}{0.0.0.0:0} added HttpConnectionFactory@6d2afb9[HTTP/1.1]
2022-11-24T16:55:16,600 | DEBUG | paxweb-config-1-thread-1 | JettyAlpnServerConnectionFactory | 86 - org.eclipse.jetty.util - 9.4.18.v20190429 | protocols: [acme-tls/1,  http/1.1]
2022-11-24T16:55:16,602 | DEBUG | paxweb-config-1-thread-1 | AbstractConnector                | 86 - org.eclipse.jetty.util - 9.4.18.v20190429 | ServerConnector@3e3fa5f2{SSL,[ssl]}{0.0.0.0:0} added SslConnectionFactory@5c245fb5{SSL->alpn}
2022-11-24T16:55:16,604 | DEBUG | paxweb-config-1-thread-1 | AbstractConnector                | 86 - org.eclipse.jetty.util - 9.4.18.v20190429 | ServerConnector@3e3fa5f2{SSL,[ssl, alpn]}{0.0.0.0:0} added JettyAlpnServerConnectionFactory@7670b8c{[alpn],http/1.1,[acme-tls/1, http/1.1]}
2022-11-24T16:55:16,605 | DEBUG | paxweb-config-1-thread-1 | AbstractConnector                | 86 - org.eclipse.jetty.util - 9.4.18.v20190429 | ServerConnector@3e3fa5f2{null,[alpn, ssl]}{0.0.0.0:0} removed SslConnectionFactory@5c245fb5{SSL->alpn}
2022-11-24T16:55:16,606 | DEBUG | paxweb-config-1-thread-1 | AbstractConnector                | 86 - org.eclipse.jetty.util - 9.4.18.v20190429 | ServerConnector@3e3fa5f2{SSL,[alpn, ssl]}{0.0.0.0:0} added SslConnectionFactory@495897b{SSL->http/1.1}
2022-11-24T16:55:16,607 | DEBUG | paxweb-config-1-thread-1 | AbstractConnector                | 86 - org.eclipse.jetty.util - 9.4.18.v20190429 | ServerConnector@3e3fa5f2{SSL,[alpn, ssl, http/1.1]}{0.0.0.0:0} added HttpConnectionFactory@4746ac2e[HTTP/1.1]
2022-11-24T16:55:16,610 | DEBUG | paxweb-config-1-thread-1 | AbstractConnector                | 86 - org.eclipse.jetty.util - 9.4.18.v20190429 | ServerConnector@39e19a84{HTTP/1.1,[http/1.1]}{0.0.0.0:0} added HttpConnectionFactory@665dd5f[HTTP/1.1]
2022-11-24T16:55:16,653 | INFO  | FelixStartLevel  | CommandExtension                 | 63 - org.apache.karaf.shell.core - 4.2.6 | Registering commands for bundle org.apache.karaf.event/4.2.6
2022-11-24T16:55:16,666 | INFO  | paxweb-config-1-thread-1 | JettyServerImpl                  | 102 - org.ops4j.pax.web.pax-web-jetty - 7.2.10 | Pax Web available at [0.0.0.0]:[8443]
2022-11-24T16:55:16,666 | INFO  | paxweb-config-1-thread-1 | JettyServerImpl                  | 102 - org.ops4j.pax.web.pax-web-jetty - 7.2.10 | Pax Web available at [0.0.0.0]:[443]
2022-11-24T16:55:16,667 | INFO  | paxweb-config-1-thread-1 | JettyServerImpl                  | 102 - org.ops4j.pax.web.pax-web-jetty - 7.2.10 | Pax Web available at [0.0.0.0]:[80]

....

2022-11-24T16:55:18,009 | INFO  | paxweb-config-1-thread-1 | Server                           | 86 - org.eclipse.jetty.util - 9.4.18.v20190429 | jetty-9.4.18.v20190429; built: 2019-04-29T20:42:08.989Z; git: e1bc35120a6617ee3df052294e433f3a25ce7097; jvm 1.8.0_322-b06
2022-11-24T16:55:18,025 | DEBUG | paxweb-config-1-thread-1 | AbstractHandler                  | 86 - org.eclipse.jetty.util - 9.4.18.v20190429 | starting JettyServerWrapper@44479759{STARTING}[9.4.18.v20190429]
2022-11-24T16:55:18,025 | DEBUG | paxweb-config-1-thread-1 | AbstractHandler                  | 86 - org.eclipse.jetty.util - 9.4.18.v20190429 | starting JettyServerHandlerCollection@5028a3d8{STARTING}
2022-11-24T16:55:18,026 | DEBUG | paxweb-config-1-thread-1 | AbstractHandler                  | 86 - org.eclipse.jetty.util - 9.4.18.v20190429 | starting SecuredRedirectHandler@192037a2{STARTING}
2022-11-24T16:55:18,027 | DEBUG | paxweb-config-1-thread-1 | AcceptRateLimit                  | 86 - org.eclipse.jetty.util - 9.4.18.v20190429 | AcceptLimit accept<10 rate<Rate@14ff572d{count=0,max=0,rate=0 per 1000 MILLISECONDS} in [0.0.0.0:8443@5c863fa9{SSL,[ssl, http/1.1]}{0.0.0.0:8443}, 0.0.0.0:443@3e3fa5f2{SSL,[alpn, ssl, http/1.1]}{0.0.0.0:443}, 0.0.0.0:80@39e19a84{HTTP/1.1,[http/1.1]}{0.0.0.0:80}] for {}
2022-11-24T16:55:18,028 | DEBUG | paxweb-config-1-thread-1 | ConnectionLimit                  | 86 - org.eclipse.jetty.util - 9.4.18.v20190429 | ConnectionLimit 1000 for [0.0.0.0:8443@5c863fa9{SSL,[ssl, http/1.1]}{0.0.0.0:8443}, 0.0.0.0:443@3e3fa5f2{SSL,[alpn, ssl, http/1.1]}{0.0.0.0:443}, 0.0.0.0:80@39e19a84{HTTP/1.1,[http/1.1]}{0.0.0.0:80}]
2022-11-24T16:55:18,037 | DEBUG | paxweb-config-1-thread-1 | AbstractHandler                  | 86 - org.eclipse.jetty.util - 9.4.18.v20190429 | starting ErrorHandler@6769d977{STARTING}
2022-11-24T16:55:18,350 | INFO  | paxweb-config-1-thread-1 | SslContextFactory                | 86 - org.eclipse.jetty.util - 9.4.18.v20190429 | x509=X509@2fbe1565(karaf,h=[gaston-schul.com],w=[]) for SslContextFactory@5e356209[provider=null,keyStore=file:///C:/Users/betzm/Development/karaf/runtime-3.1.1%20-%20Vaadin/etc/keystore/gastonschul.p12,trustStore=null]
2022-11-24T16:55:18,454 | INFO  | paxweb-config-1-thread-1 | AbstractConnector                | 86 - org.eclipse.jetty.util - 9.4.18.v20190429 | Started 0.0.0.0:8443@5c863fa9{SSL,[ssl, http/1.1]}{0.0.0.0:8443}
2022-11-24T16:55:18,459 | INFO  | paxweb-config-1-thread-1 | SslContextFactory                | 86 - org.eclipse.jetty.util - 9.4.18.v20190429 | x509=X509@70c77d62(gastonschul,h=[abeel.eu],w=[abeel.eu]) for SslContextFactory@63e569ca[provider=null,keyStore=file:///C:/Users/betzm/Development/karaf/runtime-3.1.1%20-%20Vaadin/etc/keystore/gastonschulcert.jks,trustStore=null]
2022-11-24T16:55:18,460 | INFO  | paxweb-config-1-thread-1 | SslContextFactory                | 86 - org.eclipse.jetty.util - 9.4.18.v20190429 | x509=X509@610401ba(le-802bb6a4-0d1f-47dc-915a-bd4ba2a0d83a,h=[abeel.eu],w=[abeel.eu]) for SslContextFactory@63e569ca[provider=null,keyStore=file:///C:/Users/betzm/Development/karaf/runtime-3.1.1%20-%20Vaadin/etc/keystore/gastonschulcert.jks,trustStore=null]
2022-11-24T16:55:18,477 | INFO  | paxweb-config-1-thread-1 | AbstractConnector                | 86 - org.eclipse.jetty.util - 9.4.18.v20190429 | Started 0.0.0.0:443@3e3fa5f2{SSL,[alpn, ssl, http/1.1]}{0.0.0.0:443}
2022-11-24T16:55:18,489 | INFO  | paxweb-config-1-thread-1 | AbstractConnector                | 86 - org.eclipse.jetty.util - 9.4.18.v20190429 | Started 0.0.0.0:80@39e19a84{HTTP/1.1,[http/1.1]}{0.0.0.0:80}
2022-11-24T16:55:18,490 | INFO  | paxweb-config-1-thread-1 | Server                           | 86 - org.eclipse.jetty.util - 9.4.18.v20190429 | Started @7172ms

**Comment by grgrzybek** [comment]
ok... so is it working? :)

**Comment by Maurice-Betzel** [comment]
It does not, the ALPN class is nowhere to be found. Even not from the extended folder that is supposed to add the packages to the bundle 0 classpath.

**Comment by grgrzybek** [comment]
If you add it to lib/ext, you still have to add `org.eclipse.jetty.alpn` package as _exported by system bundle_ - in `etc/config.properties`, `org.osgi.framework.system.packages.extra` property (that's what I do in Fuse with BouncyCastle packages).

**Comment by Maurice-Betzel** [comment]
I did, using bouncy as well 😉. Some research:
Changes for libraries/applications directly using Jetty ALPN APIs
Libraries or applications that are directly using the Jetty ALPN APIs (the org.eclipse.jetty.alpn.ALPN and related classes) should now be modified to detect whether the backported OpenJDK ALPN APIs are available. If the backported OpenJDK ALPN APIs are available, libraries or applications must use them; otherwise they must fall back to use the Jetty ALPN APIs (like they were doing in the past).

For example, the Jetty project is using the Jetty ALPN APIs in artifact jetty-alpn-openjdk8-[client|server]. The classes in that Jetty artifact have been changed like described above, starting from Jetty version 9.4.28.v20200408.

Changes for applications indirectly using ALPN
Applications that are using Java 8 and that depend on libraries that provide ALPN support (such as the jetty-alpn-openjdk8-[client|server] artifact described above) must modify the way they are started.

For an application that is still using an OpenJDK version prior to 8u252, the typical command line requires the alpn-boot jar in the bootclasspath and a library that uses the Jetty ALPN APIs (here as an example, jetty-alpn-openjdk8-server) in the classpath:

/opt/openjdk-8u242/bin/java -Xbootclasspath/p:/path/to/alpn-boot-8.1.13.v20181017.jar -classpath jetty-alpn-openjdk8-server-9.4.27.v20200227:...
For the same application that wants to use OpenJDK 8u252 or later, the command line becomes:

/opt/openjdk-8u252/bin/java -classpath jetty-alpn-openjdk8-server-9.4.28.v20200408:...
That is, the -Xbootclasspath option must be removed and the library must be upgraded to a version that supports the backported OpenJDK ALPN APIs.

Tomorrow we’ll see…

**Comment by Maurice-Betzel** [comment]
THIS is a interesting use of  ALPN: https://github.com/eclipse/jetty.project/blob/jetty-9.4.30.v20200611/jetty-alpn/jetty-alpn-openjdk8-server/src/main/java/org/eclipse/jetty/alpn/openjdk8/server/OpenJDK8ServerALPNProcessor.java

**Comment by Maurice-Betzel** [comment]
Moin, the bundles are resolving now and the ALPN processor is registered and ready for the ACME challenge implementation.
Since I use OpenJDK 8u252 or later, ALPN is not needed as on the extended classpath as a boot feature. I am using the mortbay ALPN bundle for reference and not the naked one as provided by the Jetty project, as PAX WEB JETTY 7.x has an optional dependency on the mortbay bundle and if it loads and initializes my ALPN processor, which is using the ALPN API, this should match due to the shared classloader between pax-web-jetty and the fragment containing the connection factory.
I created an API fragment bundle containing a AlpnServerConnectionFactory and AlpnServerConnection that the pax-web-jetty bundle will host so it can load and create the classes if the Jetty XML gets parsed. The factory has a OSGi ServiceTracker that tracks ALPNProcessor.Server services, providing the ALPN processor for the AMCE TLS challenge.
It always seems so simple once it is running, now I need a test client.

**Comment by grgrzybek** [comment]
Thanks for the live analysis ;) I'm sure it'll be useful for someone else in the future.
