### ISSUE TITLE
NoClassDefFoundError: org/apache/xpath/XPath pax-web with JSTL tag XML

### ISSUE THREAD

**Issue by jkevan** [ops4j/org.ops4j.pax.web#1807]
We are using ops4j pax web bundle in version 7.3.7 witch is embedding JSTL:

```
<dependency>
			<groupId>org.jboss.spec.javax.servlet.jstl</groupId>
			<artifactId>jboss-jstl-api_1.2_spec</artifactId>
			<version>1.1.4.Final</version>
			<exclusions>
				<exclusion>
					<groupId>org.jboss.spec.javax.servlet.jsp</groupId>
					<artifactId>jboss-jsp-api_2.3_spec</artifactId>
				</exclusion>
				<exclusion>
					<groupId>xalan</groupId>
					<artifactId>xalan</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.jboss.spec.javax.el</groupId>
					<artifactId>jboss-el-api_3.0_spec</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.jboss.spec.javax.servlet</groupId>
					<artifactId>jboss-servlet-api_3.1_spec</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
```

And we have error when using the tag lib: `<%@ taglib uri="http://java.sun.com/jsp/jstl/xml" prefix="x"%>`

Example:
```
<%
   String unXML = "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?><plan><nombre>Graduado o Graduada en IngenierÃ­a Agroalimentaria y del Medio Rural por la Universidad PÃºblica de Navarra</nombre><tipo>5</tipo></plan>";
   pageContext.setAttribute("unXML", unXML);
%>
    
<x:parse var="datosPlan" xml="${unXML}" />
<x:set var="foo" select="$datosPlan/plan/tipo" />
```

We are facing this error:
```
Caused by: java.lang.NoClassDefFoundError: org/apache/xpath/XPath
        at org.apache.taglibs.standard.tag.common.xml.SetTag.setSelect(SetTag.java:74) ~[standard-1.1.2.jar:1.1.2]
        at org.apache.jsp.modules.xmltest.jnt_005fxmltest.html.xmltest_jsp._jspx_meth_x_005fset_005f0(xmltest_jsp.java:236) ~[?:?]
        at org.apache.jsp.modules.xmltest.jnt_005fxmltest.html.xmltest_jsp._jspService(xmltest_jsp.java:151) ~[?:?]
        at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70) ~[jasper.jar:9.0.65]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) ~[servlet-api.jar:4.0.FR]
        at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:476) ~[jasper.jar:9.0.65]
        at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:385) ~[jasper.jar:9.0.65]
        at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:329) ~[jasper.jar:9.0.65]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) ~[servlet-api.jar:4.0.FR]
        at org.ops4j.pax.web.jsp.JspServletWrapper$2.call(JspServletWrapper.java:157) ~[?:?]
        at org.ops4j.pax.web.jsp.JspServletWrapper$2.call(JspServletWrapper.java:153) ~[?:?]
        at org.ops4j.pax.swissbox.core.ContextClassLoaderUtils.doWithClassLoader(ContextClassLoaderUtils.java:60) ~[pax-swissbox-core-1.8.3.jar:?]
```

I put breakpoint in the failing function: 
`at org.apache.taglibs.standard.tag.common.xml.SetTag.setSelect(SetTag.java:74)` from` jboss-jstl-api_1.2_spec`
It's correctly using the bundle classloader from` org.ops4j.pax.web.pax-web-jsp` bundle.
But the class: `org/apache/xpath/XPath` is not found.

Could it be that this jboss JSTL implementation depends on Xalan, and Xalan is actually manually exclude from the maven dependency ?
Do you have an idea how I could workaround the issue ? I don't know yet if I can tweek the ` org.ops4j.pax.web.pax-web-jsp` bundle to make it imports the necessary classes.

**Comment by jkevan** [comment]
Thank for the explanation.
In deed it was correctly set on our side on the `org.osgi.framework.system.packages.extra`
but not in:` org.osgi.framework.bootdelegation`

It would not have been necessary to add it to the bootdelegation in case there would have an optional import package on those packages inside the pax-web-jsp. Since they are correctly exported by the system bundle using `org.osgi.framework.system.packages.extra` or I am missing something ?

Anyway, thx for the helps we can now have this tag lib working in our environment.
And we can close the current issue.

**Comment by grgrzybek** [comment]
but indeed - let me keep this issue open - I'll remember to add optional `org.apache.xpath` import. Thanks for reporting!

**Comment by grgrzybek** [comment]
I added 4 optional imports:
```
    org.apache.xml.dtm;resolution := optional
    org.apache.xml.utils;resolution := optional
    org.apache.xpath;resolution := optional
    org.apache.xpath.objects;resolution := optional
```
