### ISSUE TITLE
[8.0.x][KARAF-7773] Too many initializations in simple WAB + filter scenario

### ISSUE THREAD

**Issue by grgrzybek** [ops4j/org.ops4j.pax.web#1913]
See https://issues.apache.org/jira/browse/KARAF-7773

The short deployment description is:
* a bundle with one filter in an exported package
* a WAB dropped into `$KARAF_HOME/deploy` with one listener in `web.xml` which dynamically adds the imported filter from the above bundle
* touching the WAB in `deploy/`

KARAF-7773 says that the filter is being re-registered into `/` managed by OSGi context from pax-web-extender-whiteboard during redeployment.

I found that this filter is not destroyed in the meantime, but didn't observe the re-registration.

**Comment by grgrzybek** [comment]
The batch for the WAB doesn't contain the filter:
```
batch = {org.ops4j.pax.web.service.spi.task.Batch@10057} "Batch{"Deployment of Web Application "/wab-and-filter" for bundle org.ops4j.pax.web.samples.wab-using-filter/8.0.24.SNAPSHOT", size=10}"
 description: java.lang.String  = {@10095} "Deployment of Web Application "/wab-and-filter" for bundle org.ops4j.pax.web.samples.wab-using-filter/8.0.24.SNAPSHOT"
 operations: java.util.List  = {java.util.LinkedList@10094}  size = 10
  0 = {org.ops4j.pax.web.service.spi.task.TransactionStateChange@10098} "ASSOCIATE: /wab-and-filter"
  1 = {org.ops4j.pax.web.service.spi.task.ServletContextModelChange@10099} "ADD: ServletContextModel{id=ServletContextModel-141,contextPath='/wab-and-filter'}"
  2 = {org.ops4j.pax.web.service.spi.task.OsgiContextModelChange@10100} "ADD: OsgiContextModel{WAB,id=OCM-139,name='/wab-and-filter',path='/wab-and-filter',bundle=org.ops4j.pax.web.samples.wab-using-filter,context=WebContainerContextWrapper{bundle=org.ops4j.pax.web.samples.wab-using-filter [80],contextId='/wab-and-filter',delegate=org.ops4j.pax.web.extender.war.internal.WebApplicationHelper@3386aa7b}}"
  3 = {org.ops4j.pax.web.service.spi.task.OsgiContextModelChange@10101} "ASSOCIATE: OsgiContextModel{WAB,id=OCM-139,name='/wab-and-filter',path='/wab-and-filter',bundle=org.ops4j.pax.web.samples.wab-using-filter,context=WebContainerContextWrapper{bundle=org.ops4j.pax.web.samples.wab-using-filter [80],contextId='/wab-and-filter',delegate=org.ops4j.pax.web.extender.war.internal.WebApplicationHelper@3386aa7b}}"
  4 = {org.ops4j.pax.web.service.spi.task.ContextMetadataModelChange@10102} 
  5 = {org.ops4j.pax.web.service.spi.task.MimeAndLocaleMappingChange@10103} 
  6 = {org.ops4j.pax.web.service.spi.task.ServletModelChange@10104} "ADD: ServletModel{id=ServletModel-142,name='default',urlPatterns=[/],contexts=[{WAB,OCM-139,/wab-and-filter,/wab-and-filter}]} (enabled)"
  7 = {org.ops4j.pax.web.service.spi.task.EventListenerModelChange@10105} "ADD: EventListenerModel{id=EventListenerModel-143,listener='org.ops4j.pax.web.samples.wf.wab.SomeListener@436489d',contexts=[{WAB,OCM-139,/wab-and-filter,/wab-and-filter}]}"
  8 = {org.ops4j.pax.web.service.spi.task.WelcomeFileModelChange@10106} 
  9 = {org.ops4j.pax.web.service.spi.task.TransactionStateChange@10107} "DISASSOCIATE: /wab-and-filter"
 shortDescription: java.lang.String  = {@10096} "deploy /wab-and-filter"
```

Filter is added dynamically in `org.ops4j.pax.web.samples.wf.wab.SomeListener#contextInitialized()` but anyway it should be destroyed.

**Comment by grgrzybek** [comment]
OK, I explicitly handle `org.ops4j.pax.web.service.spi.task.BatchVisitor#visitFilterModelChange()` ADD change for dynamic models, but not DELETE change - in all runtimes (Jetty, Tomcat, Undertow)

**Comment by grgrzybek** [comment]
My mistake - the `Web-ContextPath` should be `/` and not `/wab-and-filter`...

**Comment by grgrzybek** [comment]
db89560b1d4a8e6078cdfc9cd937948d45b96fc7 ensures that `filter.destroy()` is called for dynamic filter (added in ServletContextListener) when using pax-web-jetty. Tomcat and Undertow runtimes were fine.

**Comment by grgrzybek** [comment]
With `/` context in the WAB, I'm getting nice
```
2023-10-27T12:52:08,468 | INFO  | paxweb-config-20-thread-1 (deploy /)                         | SomeListener                                       | 80 - org.ops4j.pax.web.samples.wab-using-filter - 8.0.24.SNAPSHOT | SomeListener.contextInitialized()
2023-10-27T12:52:08,469 | INFO  | paxweb-config-20-thread-1 (deploy /)                         | SomeListener                                       | 80 - org.ops4j.pax.web.samples.wab-using-filter - 8.0.24.SNAPSHOT | SomeListener.contextInitialized()
2023-10-27T12:52:08,469 | ERROR | paxweb-config-20-thread-1 (deploy /)                         | JettyServerWrapper                                 | 103 - org.ops4j.pax.web.pax-web-jetty - 8.0.24.SNAPSHOT | Already initialized
java.lang.RuntimeException: Already initialized
	at org.ops4j.pax.web.samples.wf.wab.SomeListener.contextInitialized(SomeListener.java:42) ~[?:?]
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:1073) ~[?:?]
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:572) ~[?:?]
	at org.ops4j.pax.web.service.jetty.internal.PaxWebServletContextHandler.callContextInitialized(PaxWebServletContextHandler.java:174) ~[?:?]
	at org.eclipse.jetty.server.handler.ContextHandler.contextInitialized(ContextHandler.java:1002) ~[?:?]
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:765) ~[?:?]
	at org.ops4j.pax.web.service.jetty.internal.PaxWebServletHandler.initialize(PaxWebServletHandler.java:164) ~[?:?]
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:379) ~[?:?]
	at org.ops4j.pax.web.service.jetty.internal.PaxWebServletContextHandler.startContext(PaxWebServletContextHandler.java:279) ~[?:?]
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:916) ~[?:?]
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:288) ~[?:?]
	at org.ops4j.pax.web.service.jetty.internal.PaxWebServletContextHandler.doStart(PaxWebServletContextHandler.java:307) ~[?:?]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73) ~[?:?]
	at org.ops4j.pax.web.service.jetty.internal.JettyServerWrapper.ensureServletContextStarted(JettyServerWrapper.java:2420) ~[?:?]
	at org.ops4j.pax.web.service.jetty.internal.JettyServerWrapper.visitTransactionStateChange(JettyServerWrapper.java:734) ~[?:?]
	at org.ops4j.pax.web.service.spi.task.TransactionStateChange.accept(TransactionStateChange.java:35) ~[?:?]
	at org.ops4j.pax.web.service.spi.task.Batch.accept(Batch.java:430) ~[?:?]
	at org.ops4j.pax.web.service.jetty.internal.JettyServerController.sendBatch(JettyServerController.java:168) ~[?:?]
	at org.ops4j.pax.web.service.internal.HttpServiceEnabled$WebAppWebContainer.lambda$sendBatch$0(HttpServiceEnabled.java:2676) ~[?:?]
	at org.ops4j.pax.web.service.spi.model.ServerModel.lambda$run$2(ServerModel.java:541) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700) [?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```
