### ISSUE TITLE
Cannot find class javax.servlet.descriptor.JspPropertyGroupDescriptor

### ISSUE THREAD

**Issue by rodehav** [ops4j/org.ops4j.pax.web#1921]
I am using Karaf 4.4.4 with Pax-Web 8.0.22.

I get the following error in the log:
```
2023-11-30T17:55:19,274 | ERROR | [iPOJO] pool-1-thread-1 | web-console                      | 108 - se.digia.seco.web.web-console - 3.1.0.SNAPSHOT | [ERROR]  : Cannot create the proxy object
java.lang.NoClassDefFoundError: javax/servlet/descriptor/JspPropertyGroupDescriptor
at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?]
at java.lang.Class.privateGetDeclaredMethods(Class.java:3402) ~[?:?]
at java.lang.Class.privateGetPublicMethods(Class.java:3427) ~[?:?]
at java.lang.Class.getMethods(Class.java:2019) ~[?:?]
at org.apache.felix.ipojo.handlers.dependency.ProxyGenerator.dumpProxy(ProxyGenerator.java:89) ~[!/:?]
at org.apache.felix.ipojo.handlers.dependency.Dependency$SmartProxyFactory.getProxyClass(Dependency.java:1133) ~[!/:?]
at org.apache.felix.ipojo.handlers.dependency.Dependency$SmartProxyFactory.getProxy(Dependency.java:1151) [!/:?]
at org.apache.felix.ipojo.handlers.dependency.Dependency.start(Dependency.java:516) [!/:?]
at org.apache.felix.ipojo.handlers.dependency.DependencyHandler.__M_start(DependencyHandler.java:496) [!/:?]
at org.apache.felix.ipojo.handlers.dependency.DependencyHandler.start(DependencyHandler.java) [!/:?]
at org.apache.felix.ipojo.HandlerManager.start(HandlerManager.java:136) [!/:?]
at org.apache.felix.ipojo.InstanceManager.start(InstanceManager.java:421) [!/:?]
at org.apache.felix.ipojo.ComponentFactory.createInstance(ComponentFactory.java:179) [!/:?]
at org.apache.felix.ipojo.IPojoFactory.createComponentInstance(IPojoFactory.java:319) [!/:?]
at org.apache.felix.ipojo.IPojoFactory.createComponentInstance(IPojoFactory.java:240) [!/:?]
at org.apache.felix.ipojo.extender.internal.linker.ManagedType$InstanceSupport$1.call(ManagedType.java:312) [!/:?]
at org.apache.felix.ipojo.extender.internal.linker.ManagedType$InstanceSupport$1.call(ManagedType.java:306) [!/:?]
at org.apache.felix.ipojo.extender.internal.queue.JobInfoCallable.call(JobInfoCallable.java:114) [!/:?]
at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassNotFoundException: javax.servlet.descriptor.JspPropertyGroupDescriptor not found by org.ops4j.pax.web.pax-web-api [94]
at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1591) ~[?:?]
at org.apache.felix.framework.BundleWiringImpl.access$300(BundleWiringImpl.java:79) ~[?:?]
at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1976) ~[?:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
... 22 more
```
In Pax-Web 7.3.23 (used in Karaf 4.3.3) the following bundle was included:

* javax.servlet-api/3.1.0

In Pax-Web 8.0.22 (used in Karaf 4.4.4) it has been replaced by the following pair:

* jakarta.servlet-api/4.0.4
* pax-web-compatibility-servlet31/8.0.22

I am using Servlet 3.1 which was provided cleanly in Pax-Web 7.3.23. But in 8.0.22 it is instead provided by the Servlet 4.0 bundle in combination with a fragment that (if I understand correctly) re-exports that code as version 3.1. Correct me if I am wrong.

This setup doesn't seem to work with iPojo.

Looking at the bundle org.ops4j.pax.web/pax-web-api/8.0.22, it seems like it only imports the following javax.servlet packages:
```
  javax.servlet; version="[3.1, 5)",
  javax.servlet.annotation; version="[3.1, 5)",
  javax.servlet.http; version="[3.1, 5)"
```
...but not
```
  javax.servlet.descriptor
```
If I add the following:
```
  javax.servlet.descriptor;version="[3.1,5)"
```
To the Import-Package section of the `MANIFEST.MF` of the pax-we-api jar, then it works. It would be great if this import could be added to Pax-Web.

This has been discussed on the mailing list: https://groups.google.com/g/ops4j/c/qMSZT4RNRqc

**Comment by grgrzybek** [comment]
Please give me some time to check why Felix iPojo loads this class through pax-web-api...

**Comment by rodehav** [comment]
Yeah, it would be great if you could figure it out.

Thanks,

/Bengt

Den ons 6 dec. 2023 kl 12:57 skrev Grzegorz Grzybek <
***@***.***>:

**Comment by grgrzybek** [comment]
@rodehav hi

I had first glance at the issue and what I see is that:
* Latest `org.apache.felix.ipojo` bundle is from 2014-12-16 - version 1.12.1
* this version uses ASM 5...

static `org.apache.felix.ipojo.handlers.dependency.ProxyGenerator#dumpProxy()` method does ASM analysis of some classes for which some proxies (no idea how ipojo works and why it does need proxies) are generated. I didn't try to reproduce, because from stack trace I see you're using some custom console (`se.digia.seco.web.web-console`).

What I can do is simply add this import you need and release new Pax Web 8 ;)
