### ISSUE TITLE
[8.0.x] Wrong type of exception when HttpService tries to unregister unexisting registration

### ISSUE THREAD

**Issue by jherkel** [ops4j/org.ops4j.pax.web#1990]
I try to unregister a resource that wasn't registered. Javadoc says that HttpService.unregister method throws IllegalArgumentException in case when resource doesn't exist. But I can see java.lang.Throwable. 

```
java.lang.RuntimeException: Alias "/websetup/assets" was never registered by tech.pantheon.chronos.websetup.ui [281]
	at org.ops4j.pax.web.service.internal.HttpServiceEnabled.lambda$doUnregisterServlet$2(HttpServiceEnabled.java:707) ~[?:?]
	at org.ops4j.pax.web.service.spi.model.ServerModel.lambda$run$2(ServerModel.java:541) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
	Suppressed: java.lang.Throwable
		at org.ops4j.pax.web.service.spi.model.ServerModel.run(ServerModel.java:535) ~[?:?]
		at org.ops4j.pax.web.service.internal.HttpServiceEnabled.doUnregisterServlet(HttpServiceEnabled.java:589) ~[?:?]
		at org.ops4j.pax.web.service.internal.HttpServiceEnabled.unregister(HttpServiceEnabled.java:549) ~[?:?]
		at org.ops4j.pax.web.service.internal.HttpServiceProxy.unregister(HttpServiceProxy.java:186) ~[?:?]
		at tech.pantheon.chronos.websetup.ui.service.WebSetupComponent.removeResources(WebSetupComponent.java:118) ~[?:?]
		at tech.pantheon.chronos.websetup.ui.service.WebSetupComponent.removeHttpService(WebSetupComponent.java:68) ~[?:?]
		at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
		at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
		at org.apache.felix.scr.impl.inject.methods.BaseMethod.invokeMethod(BaseMethod.java:245) ~[!/:?]
		at org.apache.felix.scr.impl.inject.methods.BaseMethod.access$500(BaseMethod.java:41) ~[!/:?]
		at org.apache.felix.scr.impl.inject.methods.BaseMethod$Resolved.invoke(BaseMethod.java:687) ~[!/:?]
```

My environment: Apache Karaf 4.4.6 (Pax Web 8.0.27)

**Comment by grgrzybek** [comment]
Good catch @jherkel let me think how to solve it quickly ;)

**Comment by grgrzybek** [comment]
My fix is not to wrap `RuntimeException` derived exceptions (like `IllegalArgumentException`) within another `RuntimneException`. I'm just checking the tests and pushing the fix.
